/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Movimentacao;

import Banco.BancoFuncoes;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class DemonstrativoVendaBalcao extends javax.swing.JFrame {

    BancoFuncoes bf = new BancoFuncoes();
    public DemonstrativoVendaBalcao() {
        initComponents();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); 
        this.setLocationRelativeTo(null);
        
           gridDemo.setModel(  
      new DefaultTableModel(  
      new Object[] []{ },  
      new String[] {"N°Pedido","Produtos","Qtde","Preco","Total","Data"}) {  
  
   public boolean isCellEditable(int row, int col) {  
           return false;  
   
   }}); 
         
         
         gridPagamento.setModel(  
      new DefaultTableModel(  
      new Object[] []{ },  
      new String[] {"N°Pedido","Tipo Pagt","Valor"}) {  
  
   public boolean isCellEditable(int row, int col) {  
           return false;  
   
   }}); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gridDemo = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        gridPagamento = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedido"));
        jPanel2.setLayout(null);

        gridDemo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(gridDemo);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 20, 570, 210);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 10, 590, 240);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pagamento"));
        jPanel1.setLayout(null);

        gridPagamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        gridPagamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gridPagamentoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(gridPagamento);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 20, 330, 210);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(600, 10, 350, 240);

        setBounds(0, 0, 971, 306);
    }// </editor-fold>//GEN-END:initComponents

    private void gridPagamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gridPagamentoMouseClicked

    }//GEN-LAST:event_gridPagamentoMouseClicked

    public void carregaTabela1(String npedido){
       
        String msg1 = "Produtos recuperados com sucesso";
        String msg2 = "Erro ao Recuperar Produtos";
        String vsql = "SELECT V.NPEDIDO, I.PRODUTO, I.QTDE, I.PRECO, I.TOTAL, V.DATA\n" +
"FROM VENDA V\n" +
"JOIN ITENSPEDIDO I\n" +
"ON  I.NPEDIDO = V.NPEDIDO WHERE V.NPEDIDO = "+npedido+"";


        bf.tabelaDemonstrativoBalcao(vsql, msg1, msg2, gridDemo);
  
    }
    
    public void carregaTabela2(String npedido){
       
        String msg1 = "Produtos recuperados com sucesso";
        String msg2 = "Erro ao Recuperar Produtos";
        String vsql = "SELECT npedido,formapagamento,total from venda where npedido = "+npedido+"";


        bf.tabelaDemonstrativoPagamento(vsql, msg1, msg2, gridPagamento);
  
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DemonstrativoVendaBalcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DemonstrativoVendaBalcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DemonstrativoVendaBalcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DemonstrativoVendaBalcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DemonstrativoVendaBalcao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable gridDemo;
    public javax.swing.JTable gridPagamento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
