/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Funcionario;

import Banco.Banco;
import Banco.BancoCep;
import Banco.BancoFuncoes;
import BancoObjeto.ObjetoCliente;
import BancoObjeto.ObjetoFuncionario;
import Funcoes.LimitarCampos;
import Funcoes.ValidaCnpj;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.alfredlibrary.validadores.CPF;

/**
 *
 * @author Usuario
 */
public class Funcionario extends javax.swing.JPanel {

    BancoFuncoes bf = new BancoFuncoes();
    Banco ba = new Banco();
    BancoCep bacep = new BancoCep();
    public Funcionario() {
        initComponents();
        
        escondeMotoBoy();
        
        // BLOQUEA A EDIÇÃO DA JTABLE
        gridFuncionario.setModel(  
      new DefaultTableModel(  
      new Object[] []{ },  
      new String[] {"nomeFun", "sexoFun", "CPF", "RG","Telefone", "Ceular", "Setor", "MotoBoy", "Situacao" }) {  
  
   public boolean isCellEditable(int row, int col) {  
           return false;  
   
   }}); 
          
        
        
        
        
        
         txt_cpfFun.addFocusListener(new java.awt.event.FocusAdapter() {  
              public void focusLost(java.awt.event.FocusEvent evt) {  
                  jTextField1FocusLostCpf(evt);  
              }  
          });
         
         txt_cepFun.addFocusListener(new java.awt.event.FocusAdapter() {  
              public void focusLost(java.awt.event.FocusEvent evt) {  
                  jTextField1FocusLostCep(evt);  
              }  
          });  
         
         
         
         
        txt_setorFun.setDocument(new LimitarCampos(21));
        txt_nomeFun.setDocument(new LimitarCampos(55));
        txt_cepFun.setDocument(new LimitarCampos(8));
        txt_estadoFun.setDocument(new LimitarCampos(2));
        txt_cidadeFun.setDocument(new LimitarCampos(32));
        txt_bairroFun.setDocument(new LimitarCampos(40));
        txt_endeFun.setDocument(new LimitarCampos(60));
        txtCompleFun.setDocument(new LimitarCampos(50));
        txtNumFun.setDocument(new LimitarCampos(6));
        txtPlacaMoto.setDocument(new LimitarCampos(7));
        txtCnh.setDocument(new LimitarCampos(11));
        txtModeloMoto.setDocument(new LimitarCampos(15));

        
        
        carregaTabela();
        painel.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFuncionario = new javax.swing.JInternalFrame();
        TabFuncionario = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        jButton20 = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        jButton16 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnAlterarFuncionario = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        Desativar = new javax.swing.JButton();
        jSeparator16 = new javax.swing.JToolBar.Separator();
        jButton15 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txt_estadoFun = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txt_bairroFun = new javax.swing.JFormattedTextField();
        jLabel28 = new javax.swing.JLabel();
        txt_endeFun = new javax.swing.JFormattedTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txt_cepFun = new javax.swing.JFormattedTextField();
        txt_cidadeFun = new javax.swing.JTextField();
        txtNumFun = new javax.swing.JTextField();
        txtCompleFun = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        txt_celFun = new javax.swing.JFormattedTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txt_telFun = new javax.swing.JFormattedTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_cpfFun = new javax.swing.JFormattedTextField();
        txt_nomeFun = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_rgFun = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_setorFun = new javax.swing.JTextField();
        cmb_sexoFun = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_nasciFun = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        checkMotoBoy = new javax.swing.JCheckBox();
        labelPlaca = new javax.swing.JLabel();
        labelCnh = new javax.swing.JLabel();
        labelModelo = new javax.swing.JLabel();
        txtPlacaMoto = new javax.swing.JTextField();
        txtCnh = new javax.swing.JTextField();
        txtModeloMoto = new javax.swing.JTextField();
        painel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        comboSituacao = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gridFuncionario = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnPesquisa = new javax.swing.JButton();
        txtPesquisa = new javax.swing.JFormattedTextField();

        setLayout(null);

        internalFuncionario.setClosable(true);
        internalFuncionario.setTitle("Funcionário");
        internalFuncionario.setVisible(true);
        internalFuncionario.getContentPane().setLayout(null);

        TabFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TabFuncionarioMousePressed(evt);
            }
        });

        jPanel2.setLayout(null);

        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/procurar.png"))); // NOI18N
        jButton20.setText("Consultar");
        jButton20.setFocusable(false);
        jButton20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton20.setMargin(new java.awt.Insets(2, 25, 2, 25));
        jButton20.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton20);
        jToolBar2.add(jSeparator7);

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salvar.png"))); // NOI18N
        jButton16.setText("Inserir");
        jButton16.setFocusable(false);
        jButton16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton16.setMargin(new java.awt.Insets(2, 25, 2, 25));
        jButton16.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton16);
        jToolBar2.add(jSeparator1);

        btnAlterarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/atualizar.png"))); // NOI18N
        btnAlterarFuncionario.setText("Alterar");
        btnAlterarFuncionario.setFocusable(false);
        btnAlterarFuncionario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAlterarFuncionario.setMargin(new java.awt.Insets(2, 25, 2, 25));
        btnAlterarFuncionario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAlterarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarFuncionarioActionPerformed(evt);
            }
        });
        jToolBar2.add(btnAlterarFuncionario);
        jToolBar2.add(jSeparator10);

        Desativar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/delete.png"))); // NOI18N
        Desativar.setText("Desativar Funcionario");
        Desativar.setFocusable(false);
        Desativar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Desativar.setMargin(new java.awt.Insets(2, 25, 2, 25));
        Desativar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Desativar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesativarActionPerformed(evt);
            }
        });
        jToolBar2.add(Desativar);
        jToolBar2.add(jSeparator16);

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/novo.png"))); // NOI18N
        jButton15.setText("Limpar Campos");
        jButton15.setFocusable(false);
        jButton15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton15.setMargin(new java.awt.Insets(2, 25, 2, 25));
        jButton15.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton15);

        jPanel2.add(jToolBar2);
        jToolBar2.setBounds(0, 0, 1050, 80);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));
        jPanel5.setLayout(null);

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setText("Cep:");
        jPanel5.add(jLabel30);
        jLabel30.setBounds(10, 20, 40, 30);

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setText("UF:");
        jPanel5.add(jLabel27);
        jLabel27.setBounds(230, 20, 40, 30);
        jPanel5.add(txt_estadoFun);
        txt_estadoFun.setBounds(260, 20, 40, 30);

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel33.setText("Cidade: ");
        jPanel5.add(jLabel33);
        jLabel33.setBounds(10, 60, 50, 30);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("Bairro: ");
        jPanel5.add(jLabel24);
        jLabel24.setBounds(360, 60, 50, 30);
        jPanel5.add(txt_bairroFun);
        txt_bairroFun.setBounds(430, 60, 250, 30);

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setText("Endereço:");
        jPanel5.add(jLabel28);
        jLabel28.setBounds(10, 110, 70, 30);
        jPanel5.add(txt_endeFun);
        txt_endeFun.setBounds(100, 110, 340, 30);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setText("N°:");
        jPanel5.add(jLabel25);
        jLabel25.setBounds(450, 110, 40, 30);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Complemento: ");
        jPanel5.add(jLabel23);
        jLabel23.setBounds(10, 150, 100, 30);

        try {
            txt_cepFun.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel5.add(txt_cepFun);
        txt_cepFun.setBounds(100, 20, 100, 30);
        jPanel5.add(txt_cidadeFun);
        txt_cidadeFun.setBounds(100, 60, 230, 30);
        jPanel5.add(txtNumFun);
        txtNumFun.setBounds(480, 110, 80, 30);
        jPanel5.add(txtCompleFun);
        txtCompleFun.setBounds(100, 150, 340, 30);

        jPanel2.add(jPanel5);
        jPanel5.setBounds(10, 260, 720, 190);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Contato"));
        jPanel7.setLayout(null);

        try {
            txt_celFun.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel7.add(txt_celFun);
        txt_celFun.setBounds(300, 20, 140, 30);

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel36.setText("Celular: ");
        jPanel7.add(jLabel36);
        jLabel36.setBounds(250, 20, 80, 30);

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setText("Telefone: ");
        jPanel7.add(jLabel29);
        jLabel29.setBounds(10, 20, 80, 30);

        try {
            txt_telFun.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel7.add(txt_telFun);
        txt_telFun.setBounds(70, 20, 140, 30);

        jPanel2.add(jPanel7);
        jPanel7.setBounds(10, 450, 720, 70);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Pessoal"));
        jPanel6.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("CPF:");
        jPanel6.add(jLabel7);
        jLabel7.setBounds(20, 20, 40, 30);

        try {
            txt_cpfFun.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel6.add(txt_cpfFun);
        txt_cpfFun.setBounds(60, 20, 100, 30);
        jPanel6.add(txt_nomeFun);
        txt_nomeFun.setBounds(60, 70, 370, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Nome:");
        jPanel6.add(jLabel16);
        jLabel16.setBounds(20, 70, 50, 30);

        try {
            txt_rgFun.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel6.add(txt_rgFun);
        txt_rgFun.setBounds(240, 20, 100, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("RG:");
        jPanel6.add(jLabel9);
        jLabel9.setBounds(190, 20, 40, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Setor:");
        jPanel6.add(jLabel11);
        jLabel11.setBounds(240, 120, 50, 30);

        txt_setorFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_setorFunActionPerformed(evt);
            }
        });
        jPanel6.add(txt_setorFun);
        txt_setorFun.setBounds(280, 120, 140, 30);

        cmb_sexoFun.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Feminino", "Masculino" }));
        cmb_sexoFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_sexoFunActionPerformed(evt);
            }
        });
        jPanel6.add(cmb_sexoFun);
        cmb_sexoFun.setBounds(500, 70, 100, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Sexo:");
        jPanel6.add(jLabel8);
        jLabel8.setBounds(450, 70, 50, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Data de nascimento: ");
        jPanel6.add(jLabel14);
        jLabel14.setBounds(20, 120, 130, 30);

        try {
            txt_nasciFun.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel6.add(txt_nasciFun);
        txt_nasciFun.setBounds(140, 120, 80, 30);

        jPanel2.add(jPanel6);
        jPanel6.setBounds(10, 90, 720, 170);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Motoboy"));
        jPanel3.setLayout(null);

        checkMotoBoy.setText("Motoboy");
        checkMotoBoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMotoBoyActionPerformed(evt);
            }
        });
        jPanel3.add(checkMotoBoy);
        checkMotoBoy.setBounds(100, 20, 67, 23);

        labelPlaca.setText("Placa Moto:");
        jPanel3.add(labelPlaca);
        labelPlaca.setBounds(10, 50, 80, 30);

        labelCnh.setText("CNH:");
        jPanel3.add(labelCnh);
        labelCnh.setBounds(10, 90, 50, 20);

        labelModelo.setText("Modelo Moto:");
        jPanel3.add(labelModelo);
        labelModelo.setBounds(10, 130, 90, 30);
        jPanel3.add(txtPlacaMoto);
        txtPlacaMoto.setBounds(110, 50, 120, 30);
        jPanel3.add(txtCnh);
        txtCnh.setBounds(110, 90, 120, 30);
        jPanel3.add(txtModeloMoto);
        txtModeloMoto.setBounds(110, 130, 120, 30);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(740, 90, 260, 170);

        painel.setBorder(javax.swing.BorderFactory.createTitledBorder("Situação"));
        painel.setLayout(null);

        jLabel2.setText("Situacão:");
        painel.add(jLabel2);
        jLabel2.setBounds(20, 40, 80, 30);

        comboSituacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Ativado", "Desativado" }));
        painel.add(comboSituacao);
        comboSituacao.setBounds(90, 40, 100, 30);

        jPanel2.add(painel);
        painel.setBounds(740, 260, 260, 190);

        TabFuncionario.addTab("Registro", jPanel2);

        jPanel1.setLayout(null);

        gridFuncionario.setAutoCreateRowSorter(true);
        gridFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        gridFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gridFuncionarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(gridFuncionario);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 100, 1050, 400);

        jLabel1.setText("CPF:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(280, 50, 50, 30);

        btnPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/procurar.png"))); // NOI18N
        btnPesquisa.setText("Pesquisar");
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });
        jPanel1.add(btnPesquisa);
        btnPesquisa.setBounds(490, 30, 180, 50);

        try {
            txtPesquisa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(txtPesquisa);
        txtPesquisa.setBounds(330, 50, 130, 30);

        TabFuncionario.addTab("Pesquisa", jPanel1);

        internalFuncionario.getContentPane().add(TabFuncionario);
        TabFuncionario.setBounds(0, 0, 1070, 550);

        add(internalFuncionario);
        internalFuncionario.setBounds(0, 0, 1090, 580);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed

        String aux,nomeFun, nasciFun, endeFun, compleFun, bairroFun , cidadeFun, setorFun, loginFun, senhaFun, sexoFun,
        rgFun, cpfFun, cepFun, numFun,ufFun, telFun, celFun,motoboy = "",placamoto,cnh,modelomoto,situacao;

       
        nomeFun = txt_nomeFun.getText();
        nasciFun = txt_nasciFun.getText();
        endeFun = txt_endeFun.getText();
        compleFun = txtCompleFun.getText();
        bairroFun = txt_bairroFun.getText();
        ufFun = txt_estadoFun.getText();
        cidadeFun = txt_cidadeFun.getText();
        setorFun = txt_setorFun.getText();
        rgFun = txt_rgFun.getText();
        cpfFun = txt_cpfFun.getText();
        cepFun = txt_cepFun.getText();
        numFun = txtNumFun.getText();
        telFun = txt_telFun.getText();
        celFun = txt_celFun.getText();
        placamoto = txtPlacaMoto.getText();
        cnh = txtCnh.getText();
        modelomoto = txtModeloMoto.getText();
        situacao = "Ativado";
        sexoFun = cmb_sexoFun.getSelectedItem().toString();
        System.out.println(sexoFun);
        
        
        if(checkMotoBoy.isSelected()){
            
            motoboy += "SIM";
            
        }
        else{
            
            motoboy += "NAO";
            
        }
        

        if(sexoFun.equals("-")){
            JOptionPane.showMessageDialog(null, "Escolha o sexo");
        }
        else{
        
         if (CPF.isValido(cpfFun) == false || "111.111.111-11".equals(cpfFun) || "000.000.000-00".equals(cpfFun) || "   .   .   -  ".equals(cpfFun)  ){
         
             JOptionPane.showMessageDialog(null, "Cpf Invalido");
             
             
         }
        
             else {
             
             ba.gravaFuncionario(nomeFun, nasciFun, endeFun, compleFun, bairroFun ,
                     cidadeFun, setorFun, sexoFun, rgFun, cpfFun, cepFun, numFun, telFun,
                     celFun,ufFun,motoboy,placamoto,cnh,modelomoto,situacao);

            limpacampos();
            
        }
      }
        
    }//GEN-LAST:event_jButton16ActionPerformed

    private void btnAlterarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarFuncionarioActionPerformed

         String aux,nomeFun, nasciFun, endeFun, compleFun, bairroFun , cidadeFun, setorFun, loginFun, senhaFun, sexoFun,
        rgFun, cpfFun, cepFun, numFun,ufFun, telFun, celFun, motoboy ="", placamoto,cnh,modelomoto,situacao;

      
       
        nomeFun = txt_nomeFun.getText();
        nasciFun = txt_nasciFun.getText();
        endeFun = txt_endeFun.getText();
        compleFun = txtCompleFun.getText();
        bairroFun = txt_bairroFun.getText();
        ufFun = txt_estadoFun.getText();
        cidadeFun = txt_cidadeFun.getText();
        setorFun = txt_setorFun.getText();
        rgFun = txt_rgFun.getText();
        cpfFun = txt_cpfFun.getText();
        cepFun = txt_cepFun.getText();
        numFun = txtNumFun.getText();
        telFun = txt_telFun.getText();
        celFun = txt_celFun.getText();
        placamoto = txtPlacaMoto.getText();
        cnh = txtCnh.getText();
        modelomoto = txtModeloMoto.getText();
        situacao = comboSituacao.getSelectedItem().toString();
  
        
        
        if(checkMotoBoy.isSelected()){
            
            motoboy += "SIM";
            
        }
        else{
            
            motoboy += "NAO";
            
        }
        sexoFun = cmb_sexoFun.getSelectedItem().toString();

        if("   .   .   -  ".equals(cpfFun)){

            JOptionPane.showMessageDialog(null,"Preecha  o campo cpf");
            txt_cpfFun.requestFocus();
        }
        else{

            ba.atualizaFuncionario(nomeFun, nasciFun, endeFun, compleFun, bairroFun, ufFun,cidadeFun, setorFun, rgFun,cpfFun, cepFun, numFun, telFun, celFun,sexoFun,motoboy,placamoto,cnh,modelomoto,situacao);
            painel.setVisible(false);
        }
        
    }//GEN-LAST:event_btnAlterarFuncionarioActionPerformed

    private void txt_setorFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_setorFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_setorFunActionPerformed

    private void DesativarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesativarActionPerformed
          //String nomeFantasia = nome_fantasiaFor.getText();
        
       
            
             
        String cpf =txt_cpfFun.getText();
        String situacao = "Desativado";

        if(CPF.isValido(cpf) == false ||"   .   .   -  ".equals(cpf)){

            JOptionPane.showMessageDialog(null,"Preencha o campo CPF  corretamente para realizar uma exclusão");
            
            txt_cpfFun.requestFocus();

        }

        else{
            if (ba.desativaFuncionario(cpf,situacao)) {
                JOptionPane.showMessageDialog(null, "Desativado com sucesso");

                 limpacampos();

            }
            else {
                JOptionPane.showMessageDialog(null, "Não encontrado");
            }
        }
        
        
        
         
    }//GEN-LAST:event_DesativarActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
         ResultSet rs;

        
        String cpf = txt_cpfFun.getText();
        String sexoFun = null;
       

        
        if("   .   .   -  ".equals(cpf)){

            JOptionPane.showMessageDialog(null,"Preencha o campo Cpf para realizar uma busca");
            txt_cpfFun.requestFocus();
        }

        else{

            rs = ba.buscaFuncionario(cpf);
            try {

                if (ba.buscaFuncionario(cpf) != null) {
                    txt_rgFun.setText(rs.getString("rgFun"));
                    txt_nomeFun.setText(rs.getString("nomeFun"));
                    txt_setorFun.setText(rs.getString("setorFun"));
                    txt_nasciFun.setText(rs.getString("nasciFun"));
                    txt_cepFun.setText(rs.getString("cepFun"));
                    txt_estadoFun.setText(rs.getString("ufFun"));
                    txt_cidadeFun.setText(rs.getString("cidadeFun"));
                    txt_bairroFun.setText(rs.getString("bairroFun"));
                    txt_endeFun.setText(rs.getString("endeFun"));
                    txtCompleFun.setText(rs.getString("compleFun"));
                    txtNumFun.setText(rs.getString("numFun"));
                    txt_cpfFun.setText(txt_cpfFun.getText());
                    txt_telFun.setText(rs.getString("telFun"));
                     txt_celFun.setText(rs.getString("celFun"));    
                    sexoFun = rs.getString("sexoFun");
                    String situacao = rs.getString("Situacao");
                    comboSituacao.setSelectedItem(situacao);
                  
                     cmb_sexoFun.setSelectedItem(sexoFun);
                    
                    
                     String motoboy = rs.getString("motoboy");
                     
                     if(motoboy.equals("SIM")){
                         
                         checkMotoBoy.setSelected(true);
                         mostraMotoboy();
                         
                     }
                     else{
                         
                         checkMotoBoy.setSelected(false);
                         escondeMotoBoy();
                     }
                     
                      txtPlacaMoto.setText(rs.getString("placamoto"));  
                      txtCnh.setText(rs.getString("cnh"));  
                      txtModeloMoto.setText(rs.getString("modelomoto"));  
         
                      painel.setVisible(true);
                }
                
             
                else{

                   limpacampos();  
                }
            } catch (SQLException ex) {
            }
        }
        
        
    
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
           limpacampos();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
         DefaultTableModel modelo = (DefaultTableModel)gridFuncionario.getModel();
       
         
    gridFuncionario.removeAll();
    
    while(modelo.getRowCount() > 0){
        modelo.removeRow(0);
    }
    String cpf = txtPesquisa.getText();
    
    ObjetoFuncionario funcionariopesquisado = new ObjetoFuncionario();
    
     if(txtPesquisa.equals("   .   .   -  ") || CPF.isValido(cpf) == false){
         JOptionPane.showMessageDialog(null,"Entre com um cpf valido");
         
     }
     
     else{
     if(txtPesquisa.getText().isEmpty() == false){
        

      
            funcionariopesquisado = ba.buscaFuncionarioTabela(String.valueOf(cpf));
            if(funcionariopesquisado != null){
                modelo.addRow(new Object[]{
                  funcionariopesquisado.getNomeFun(),
                  funcionariopesquisado.getSexoFun(),
                  funcionariopesquisado.getCpfFun(),
                  funcionariopesquisado.getRgFun(),
                  funcionariopesquisado.getNasciFun(),
                  funcionariopesquisado.getUfFun(),
                  funcionariopesquisado.getCidadeFun(),
                  funcionariopesquisado.getEndeFun(),
                  funcionariopesquisado.getBairroFun(),
                  funcionariopesquisado.getCepFun(),
                  funcionariopesquisado.getNumFun(),
                  funcionariopesquisado.getCompleFun(),
                  funcionariopesquisado.getTelFun(),
                  funcionariopesquisado.getCelFun(),
                  funcionariopesquisado.getSetorFun(),
                
                
                });
            }
            else{
                JOptionPane.showMessageDialog(null, "Nenhum Cliente encontrado !!!");
            }
        
    }
  }
    gridFuncionario.repaint();
    
    txtPesquisa.setText(null);
              
    }//GEN-LAST:event_btnPesquisaActionPerformed

        // PEGA OS CAMPOS QUE ESTÃO NA JTABLE E JOGA NOS TEXTFIELDS
    
    private void gridFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gridFuncionarioMouseClicked
        
        
        if (evt.getClickCount() == 2) {  
           
            
            Object obj2 = (gridFuncionario.getValueAt(gridFuncionario.getSelectedRow(), 2));  //coluna 0  
            String cpf = obj2.toString();  
            
           
            preencheFuncionario(cpf);
            

             
             
               // QUANDO SELECIONA A LINHA NA JTABLE MUDA A ABA
              TabFuncionario.setSelectedIndex(0);   
             
        }
        
    }//GEN-LAST:event_gridFuncionarioMouseClicked

    private void cmb_sexoFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_sexoFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_sexoFunActionPerformed

    private void TabFuncionarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabFuncionarioMousePressed
        
        carregaTabela();
        
        
    }//GEN-LAST:event_TabFuncionarioMousePressed

    private void checkMotoBoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMotoBoyActionPerformed
        
        if(checkMotoBoy.isSelected()){
            
            mostraMotoboy();
            
        }
        else{
            
            escondeMotoBoy();
        }
        
        
    }//GEN-LAST:event_checkMotoBoyActionPerformed

    
    
      private void jTextField1FocusLostCpf(java.awt.event.FocusEvent evt) {
        String cpfFor = txt_cpfFun.getText();
        String cpf = cpfFor;

            if (CPF.isValido(cpfFor) == false || "111.111.111-11".equals(cpfFor) || "000.000.000-00".equals(cpfFor) || "   .   .   -  ".equals(cpfFor)  ){


          

          JOptionPane.showMessageDialog(null,"Atenção Cpf inválido");
          
          txt_cpfFun.requestFocus();
          
          
         }
        else{
         
         ValidaCnpj.formatar(cpf);
         txt_cpfFun.setText(cpf);
         System.out.println(cpf);
         
        }

    }

      
      
       private void jTextField1FocusLostCep(java.awt.event.FocusEvent evt) {  
        ResultSet rs;

        String cep = txt_cepFun.getText();

        if("".equals(cep)){

        }

        
        else{
            
            
            rs = bacep.buscaCep(cep);
            try {

                if (bacep.buscaCep(cep) != null) {

                    txt_endeFun.setText(rs.getString("desc_logradouro"));
                    txt_cidadeFun.setText(rs.getString("desc_cidade"));
                    txt_estadoFun.setText(rs.getString("flg_estado"));
                    txt_bairroFun.setText(rs.getString("desc_bairro"));
                    
                }
                else{

                }
            } catch (SQLException ex) {
            }
        } 
        
    }  
       
       
        public void carregaTabela(){
        String msg1 = "funcionario recuperados com sucesso";
        String msg2 = "Erro ao Recuperar funcionario";
        String vsql = "SELECT * from funcionario";


        bf.tabelaFuncionario(vsql, msg1, msg2, gridFuncionario);
    }
        
        public void preencheFuncionario(String cpf){
            
            
            ResultSet rs;

        
    
        String sexoFun = null;
       

     
            rs = ba.buscaFuncionario(cpf);
            try {

                if (ba.buscaFuncionario(cpf) != null) {
                    
                    txt_cpfFun.setText(rs.getString("cpfFun"));
                     txt_rgFun.setText(rs.getString("rgFun"));
                    txt_nomeFun.setText(rs.getString("nomeFun"));
                    txt_setorFun.setText(rs.getString("setorFun"));
                    txt_nasciFun.setText(rs.getString("nasciFun"));
                    txt_cepFun.setText(rs.getString("cepFun"));
                    txt_estadoFun.setText(rs.getString("ufFun"));
                    txt_cidadeFun.setText(rs.getString("cidadeFun"));
                    txt_bairroFun.setText(rs.getString("bairroFun"));
                    txt_endeFun.setText(rs.getString("endeFun"));
                    txtCompleFun.setText(rs.getString("compleFun"));
                    txtNumFun.setText(rs.getString("numFun"));
                    txt_cpfFun.setText(txt_cpfFun.getText());
                    txt_telFun.setText(rs.getString("telFun"));
                     txt_celFun.setText(rs.getString("celFun"));    
                    sexoFun = rs.getString("sexoFun");
                    
                  
                     cmb_sexoFun.setSelectedItem(sexoFun);
                    
                    
                     String motoboy = rs.getString("motoboy");
                     
                     if(motoboy.equals("SIM")){
                         
                         checkMotoBoy.setSelected(true);
                         mostraMotoboy();
                         
                     }
                     else{
                         
                         checkMotoBoy.setSelected(false);
                         escondeMotoBoy();
                     }
                     
                      txtPlacaMoto.setText(rs.getString("placamoto"));  
                      txtCnh.setText(rs.getString("cnh"));  
                      txtModeloMoto.setText(rs.getString("modelomoto"));  
                      String situacao = rs.getString("situacao");
                      comboSituacao.setSelectedItem(situacao);
                      
                      painel.setVisible(true);
                      
         
                }
                
             
                else{

                    txt_rgFun.setText("");
                    txt_nomeFun.setText("");
                    txt_setorFun.setText("");
                    txt_nasciFun.setText("");
                    txt_cepFun.setText("");
                    txt_estadoFun.setText("");
                    txt_cidadeFun.setText("");
                    txt_bairroFun.setText("");
                    txt_endeFun.setText("");
                    txtCompleFun.setText("");
                    txtNumFun.setText("");
                    txt_cpfFun.setText("");
                    txt_telFun.setText("");
                     txt_celFun.setText("");   
                }
            } catch (SQLException ex) {
            }
        }
        
        public void escondeMotoBoy(){
            
            labelPlaca.setVisible(false);
            labelCnh.setVisible(false);
            labelModelo.setVisible(false);
            txtPlacaMoto.setVisible(false);
            txtCnh.setVisible(false);
            txtModeloMoto.setVisible(false);
            
            
            
            
        }
        
        public void mostraMotoboy(){
            
            
            labelPlaca.setVisible(true);
            labelCnh.setVisible(true);
            labelModelo.setVisible(true);
            txtPlacaMoto.setVisible(true);
            txtCnh.setVisible(true);
            txtModeloMoto.setVisible(true);
            
        }
            
        public void limpacampos(){
            
            txt_nomeFun.setText("");
            txt_cpfFun.setText("");
            txt_rgFun.setText("");
            txt_nasciFun.setText("");
            txt_endeFun.setText("");
            txtCompleFun.setText("");
            txt_bairroFun.setText("");
            txt_cepFun.setText("");
            txtNumFun.setText("");
            txt_telFun.setText("");
            txt_celFun.setText("");
            txt_setorFun.setText("");
            txt_cidadeFun.setText("");
            txt_estadoFun.setText("");
            txtPlacaMoto.setText("");
            txtCnh.setText("");
            txtModeloMoto.setText("");
            checkMotoBoy.setSelected(false);
            
        }
       
       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Desativar;
    private javax.swing.JTabbedPane TabFuncionario;
    private javax.swing.JButton btnAlterarFuncionario;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JCheckBox checkMotoBoy;
    private javax.swing.JComboBox cmb_sexoFun;
    private javax.swing.JComboBox comboSituacao;
    private javax.swing.JTable gridFuncionario;
    public javax.swing.JInternalFrame internalFuncionario;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton20;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator16;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JLabel labelCnh;
    private javax.swing.JLabel labelModelo;
    private javax.swing.JLabel labelPlaca;
    private javax.swing.JPanel painel;
    private javax.swing.JTextField txtCnh;
    private javax.swing.JTextField txtCompleFun;
    private javax.swing.JTextField txtModeloMoto;
    private javax.swing.JTextField txtNumFun;
    private javax.swing.JFormattedTextField txtPesquisa;
    private javax.swing.JTextField txtPlacaMoto;
    private javax.swing.JFormattedTextField txt_bairroFun;
    private javax.swing.JFormattedTextField txt_celFun;
    private javax.swing.JFormattedTextField txt_cepFun;
    private javax.swing.JTextField txt_cidadeFun;
    private javax.swing.JFormattedTextField txt_cpfFun;
    private javax.swing.JFormattedTextField txt_endeFun;
    private javax.swing.JTextField txt_estadoFun;
    private javax.swing.JFormattedTextField txt_nasciFun;
    private javax.swing.JFormattedTextField txt_nomeFun;
    private javax.swing.JFormattedTextField txt_rgFun;
    private javax.swing.JTextField txt_setorFun;
    private javax.swing.JFormattedTextField txt_telFun;
    // End of variables declaration//GEN-END:variables
}
