/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pedidos;

import Banco.Banco;
import Banco.BancoFuncoes;
import Caixa.gridPedidos;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Paulo
 */
public class Pedidos extends javax.swing.JFrame {

    
    Banco ba = new Banco();
    BancoFuncoes bf = new BancoFuncoes();
    gridPedidos gp = new gridPedidos();
    
    public Pedidos() {
        initComponents();
        carregaMotoboy();
        desabilitaCampos();
        Cancelar.setEnabled(false);
        
         gridPedidos.setModel(  
      new DefaultTableModel(  
      new Object[] []{ },  
      new String[] {"N°Pedido", "Nome", "Telefone", "Forma Pagamento","Total",
                        "Motoboy","Situação", "Hora Pedido", "Hora Saida", "Hora Entrega"}) {  
  
   public boolean isCellEditable(int row, int col) {  
           return false;  
   
   }}); 
         
        
         
         
           gridCancelar.setModel(  
      new DefaultTableModel(  
      new Object[] []{ },  
      new String[] {"N°Pedido", "Nome", "Telefone", "Forma Pagamento","Total",
                        "Motoboy","Situação", "Hora Pedido"}) {  
  
   public boolean isCellEditable(int row, int col) {  
           return false;  
   
   }}); 
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoRadio = new javax.swing.ButtonGroup();
        grupoRadio2 = new javax.swing.ButtonGroup();
        radioCancelar = new javax.swing.ButtonGroup();
        internalPedidos = new javax.swing.JInternalFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        radioBalcao = new javax.swing.JRadioButton();
        radioEntrega = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        gridPedidos = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        comboMotoboy = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        radioSaiu = new javax.swing.JRadioButton();
        radioOK = new javax.swing.JRadioButton();
        radioNao = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtNpedido = new javax.swing.JTextField();
        btnAtualiza = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        radioBalcaoCancelar = new javax.swing.JRadioButton();
        radioEntregaCancelar = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        gridCancelar = new javax.swing.JTable();
        Cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        internalPedidos.setClosable(true);
        internalPedidos.setVisible(true);
        internalPedidos.getContentPane().setLayout(null);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanel1.setLayout(null);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo Pedido"));
        jPanel3.setLayout(null);

        grupoRadio.add(radioBalcao);
        radioBalcao.setText("Balcão");
        radioBalcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBalcaoActionPerformed(evt);
            }
        });
        jPanel3.add(radioBalcao);
        radioBalcao.setBounds(20, 30, 90, 23);

        grupoRadio.add(radioEntrega);
        radioEntrega.setText("Entrega");
        radioEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioEntregaActionPerformed(evt);
            }
        });
        jPanel3.add(radioEntrega);
        radioEntrega.setBounds(120, 30, 93, 23);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 20, 230, 70);

        gridPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        gridPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gridPedidosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(gridPedidos);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 110, 1080, 170);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.setLayout(null);

        jLabel2.setText("Motoboy:");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(10, 20, 60, 30);

        comboMotoboy.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(comboMotoboy);
        comboMotoboy.setBounds(10, 50, 230, 30);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Situação da Entrega"));
        jPanel5.setLayout(null);

        grupoRadio2.add(radioSaiu);
        radioSaiu.setText("Saiu Para Entregar");
        jPanel5.add(radioSaiu);
        radioSaiu.setBounds(12, 31, 140, 23);

        grupoRadio2.add(radioOK);
        radioOK.setText("Entrega OK");
        jPanel5.add(radioOK);
        radioOK.setBounds(10, 60, 140, 23);

        grupoRadio2.add(radioNao);
        radioNao.setText("Não Entregue");
        jPanel5.add(radioNao);
        radioNao.setBounds(10, 90, 150, 23);

        jPanel4.add(jPanel5);
        jPanel5.setBounds(250, 20, 590, 130);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(180, 280, 910, 170);

        jLabel1.setText("N° Pedido:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 320, 70, 30);

        txtNpedido.setEditable(false);
        jPanel1.add(txtNpedido);
        txtNpedido.setBounds(80, 320, 90, 30);

        btnAtualiza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/atualizar.png"))); // NOI18N
        btnAtualiza.setText("Atualizar Entrega");
        btnAtualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtualiza);
        btnAtualiza.setBounds(890, 460, 180, 40);

        jTabbedPane1.addTab("Pedidos", jPanel1);

        jPanel2.setLayout(null);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo Pedido"));
        jPanel6.setLayout(null);

        radioCancelar.add(radioBalcaoCancelar);
        radioBalcaoCancelar.setText("Balcão");
        radioBalcaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBalcaoCancelarActionPerformed(evt);
            }
        });
        jPanel6.add(radioBalcaoCancelar);
        radioBalcaoCancelar.setBounds(20, 23, 90, 30);

        radioCancelar.add(radioEntregaCancelar);
        radioEntregaCancelar.setText("Entrega");
        radioEntregaCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioEntregaCancelarActionPerformed(evt);
            }
        });
        jPanel6.add(radioEntregaCancelar);
        radioEntregaCancelar.setBounds(120, 23, 93, 30);

        jPanel2.add(jPanel6);
        jPanel6.setBounds(10, 20, 230, 70);

        gridCancelar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        gridCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gridCancelarMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(gridCancelar);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(10, 100, 1080, 170);

        Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/1444154342_close.png"))); // NOI18N
        Cancelar.setText("Cancelar Pedido");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        jPanel2.add(Cancelar);
        Cancelar.setBounds(910, 280, 170, 50);

        jTabbedPane1.addTab("Cancelar Pedidos", jPanel2);

        internalPedidos.getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 1100, 540);

        getContentPane().add(internalPedidos);
        internalPedidos.setBounds(0, 0, 1130, 600);

        setBounds(0, 0, 1170, 733);
    }// </editor-fold>//GEN-END:initComponents

    private void radioBalcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBalcaoActionPerformed

        
        if(radioBalcao.isSelected()){
            
            carregaTabelaBalcao();
            habilitaCampos();
            comboMotoboy.setEnabled(false);
            radioSaiu.setEnabled(false);
 
      
            
        }
        
    }//GEN-LAST:event_radioBalcaoActionPerformed

    private void radioEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEntregaActionPerformed
       
        
        if(radioEntrega.isSelected()){
            
            carregaTabelaEntrega();
            habilitaCampos();
            comboMotoboy.setEnabled(true);
            radioSaiu.setEnabled(true);
           
        }
        
    }//GEN-LAST:event_radioEntregaActionPerformed

    private void gridPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gridPedidosMouseClicked
        
        Object obj0 = (gridPedidos.getValueAt(gridPedidos.getSelectedRow(), 0));  //coluna 0  
            String npedido = obj0.toString();
            
            txtNpedido.setText(npedido);
            
            if(radioEntrega.isSelected()){
              if (evt.getClickCount() == 2) {    
                Object obj2 = (gridPedidos.getValueAt(gridPedidos.getSelectedRow(), 2));  //coluna 0  
            String telefone = obj2.toString();
                
                 gridEndereco gridende = new gridEndereco();
                 gridende.setVisible(true);   
                 
                 gridende.carregaTabela1(telefone);
              }
            }
            else{
                
                
            }
        
    }//GEN-LAST:event_gridPedidosMouseClicked

    private void btnAtualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizaActionPerformed
       
        String situacao="", horasaida="",horaentrega="",motoboy,npedido;
        
      motoboy = comboMotoboy.getSelectedItem().toString();
      
      
      
        SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss");  

      npedido = txtNpedido.getText();
      

      
        if(npedido.equals("")){
            
            JOptionPane.showMessageDialog(null, "Selecione o pedido");
            
        }    
        
        else{
            
        if(radioSaiu.isSelected()){
            horasaida = sdf.format(Calendar.getInstance().getTime());  
            situacao += "Saiu Para Entregar";
            ba.atualizaPedidoSaiuEntrega(npedido,situacao,horasaida,motoboy);
            gp.carregaTabelaPedidos();
        }
        
        else if(radioOK.isSelected()){
              horaentrega = sdf.format(Calendar.getInstance().getTime());  
            situacao += "Entrega OK";
            
             ba.atualizaPedidoEntregaOK(npedido,situacao,horaentrega,motoboy);
             gp.carregaTabelaPedidos();
            
        }
        
        else if(radioNao.isSelected()){
            
            situacao += "Não Entregue";
            
             ba.atualizaPedidoNaoOK(npedido,situacao,motoboy);
              gp.carregaTabelaPedidos();
        }
        
        if(radioBalcao.isSelected()){
            
            carregaTabelaBalcao();
            comboMotoboy.setEnabled(false);
            radioSaiu.setEnabled(false);
            
            
        }
        
          else if(radioEntrega.isSelected()){
            
            carregaTabelaEntrega();
            comboMotoboy.setEnabled(true);
            radioSaiu.setEnabled(true);
        }
        
        if(situacao.equals("")){
            
            JOptionPane.showMessageDialog(null, "Selecione a situação do pedido");
            
        }
     }
        
    }//GEN-LAST:event_btnAtualizaActionPerformed

    private void radioBalcaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBalcaoCancelarActionPerformed
           if(radioBalcaoCancelar.isSelected()){
            
            carregaTabelaBalcaoCancelar();
            Cancelar.setEnabled(true);
        }
    }//GEN-LAST:event_radioBalcaoCancelarActionPerformed

    private void radioEntregaCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEntregaCancelarActionPerformed
       if(radioEntregaCancelar.isSelected()){
            
            carregaTabelaEntregaCancelar();
            Cancelar.setEnabled(true);
        }
    }//GEN-LAST:event_radioEntregaCancelarActionPerformed

    private void gridCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gridCancelarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_gridCancelarMouseClicked

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        
         Object obj0 = (gridCancelar.getValueAt(gridCancelar.getSelectedRow(), 0));  //coluna 0  
            String npedido = obj0.toString();
            
            txtNpedido.setText(npedido);
            String situacao = "Cancelado";
            ba.atualizaPedidoCancelado(npedido, situacao);
            
            if(radioBalcaoCancelar.isSelected()){
                
                carregaTabelaBalcaoCancelar();
                
            }
            
            else if(radioEntregaCancelar.isSelected()){
                
                 carregaTabelaEntregaCancelar();
                
            }
            
            JOptionPane.showMessageDialog(null, "Pedido Cancelado");
        
    }//GEN-LAST:event_CancelarActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
    
    }//GEN-LAST:event_jTabbedPane1StateChanged

    /**
     * @param args the command line arguments
     */
    
    
    public void carregaMotoboy(){;
        String msg1 = "Motoboy Recuperado";
        String msg2 = "Erro ao Recuperar Motoboy ";
        String vsql = "SELECT NOMEFUN FROM FUNCIONARIO WHERE MOTOBOY = 'SIM' order by NOMEFUN" ;
        String campoSql = "NOMEFUN";

        bf.carregaDadoUnico(vsql, msg1, msg2, comboMotoboy, campoSql);
    }
    
    public void carregaTabelaBalcao(){

         String msg1 = "Itens recuperados com sucesso";
        String msg2 = "Erro ao Recuperar Pedidos";
        String vsql = "SELECT v.npedido, v.formapagamento, v.total, v.situacaoentrega,v.hora, v.hrsaida, v.horaentrega\n" +
"FROM VENDA V\n" +
"WHERE v.tipopedido = 'Pedido Balcao'";


        bf.tabelaPedidosBalcao(vsql, msg1, msg2, gridPedidos);
    }
    
     public void carregaTabelaBalcaoCancelar(){

         String msg1 = "Itens recuperados com sucesso";
        String msg2 = "Erro ao Recuperar Pedidos";
        String vsql = "SELECT v.npedido, v.formapagamento, v.total, v.situacaoentrega,v.hora, v.hrsaida, v.horaentrega\n" +
"FROM VENDA V\n" +
"WHERE v.tipopedido = 'Pedido Balcao'";


        bf.tabelaPedidosBalcao(vsql, msg1, msg2, gridCancelar);
    }
    
    public void carregaTabelaEntrega(){

         String msg1 = "Itens recuperados com sucesso";
        String msg2 = "Erro ao Recuperar Pedidos";
        String vsql = "SELECT v.npedido, c.nome, c.telefone, v.formapagamento, v.total, v.motoboy, v.situacaoentrega,v.hora, v.hrsaida, v.horaentrega\n" +
"FROM VENDA V\n" +
"JOIN CLIENTES C \n" +
"ON V.TELEFONE = C.TELEFONE\n" +
"WHERE v.tipopedido = 'Pedido Entrega'" ;


        bf.tabelaPedidosEntrega(vsql, msg1, msg2, gridPedidos);
    }
    
     public void carregaTabelaEntregaCancelar(){

         String msg1 = "Itens recuperados com sucesso";
        String msg2 = "Erro ao Recuperar Pedidos";
        String vsql = "SELECT v.npedido, c.nome, c.telefone, v.formapagamento, v.total, v.motoboy, v.situacaoentrega,v.hora, v.hrsaida, v.horaentrega\n" +
"FROM VENDA V\n" +
"JOIN CLIENTES C \n" +
"ON V.TELEFONE = C.TELEFONE\n" +
"WHERE v.tipopedido = 'Pedido Entrega'" ;


        bf.tabelaPedidosEntrega(vsql, msg1, msg2, gridCancelar);
    }
     
     public void carregaTabelaTudo(){

    }
    
    public void desabilitaCampos(){
        
        comboMotoboy.setEnabled(false);
        radioSaiu.setEnabled(false);
        radioOK.setEnabled(false);
        radioNao.setEnabled(false);  
        btnAtualiza.setEnabled(false);  
    }
    public void habilitaCampos(){
        
        comboMotoboy.setEnabled(true);
        radioSaiu.setEnabled(true);
        radioOK.setEnabled(true);
        radioNao.setEnabled(true);  
        btnAtualiza.setEnabled(true);  
    }
   
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton btnAtualiza;
    private javax.swing.JComboBox comboMotoboy;
    private javax.swing.JTable gridCancelar;
    private javax.swing.JTable gridPedidos;
    private javax.swing.ButtonGroup grupoRadio;
    private javax.swing.ButtonGroup grupoRadio2;
    public javax.swing.JInternalFrame internalPedidos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton radioBalcao;
    private javax.swing.JRadioButton radioBalcaoCancelar;
    private javax.swing.ButtonGroup radioCancelar;
    private javax.swing.JRadioButton radioEntrega;
    private javax.swing.JRadioButton radioEntregaCancelar;
    private javax.swing.JRadioButton radioNao;
    private javax.swing.JRadioButton radioOK;
    private javax.swing.JRadioButton radioSaiu;
    private javax.swing.JTextField txtNpedido;
    // End of variables declaration//GEN-END:variables
}
