/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ContaPagarReceber;

import Banco.Banco;
import Banco.BancoCep;
import Banco.BancoFuncoes;
import Funcoes.LimitarCampos;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static org.alfredlibrary.validadores.CNPJ.isValido;
import org.alfredlibrary.validadores.CPF;

/**
 *
 * @author Usuario
 */
public class ContasPagarReceber extends javax.swing.JFrame {
    BancoCep bacep = new BancoCep();
   Banco ba = new Banco();
   BancoFuncoes bf = new BancoFuncoes();
   
    public ContasPagarReceber() {
        initComponents();
        
        
           
      gridContasPagar.setModel(  
      new DefaultTableModel(  
      new Object[] []{ },  
      new String[] {"Nota_Fiscal", "Descricao", "Dt_Recebimento", "Dt_Emissao", "Dt_Vencimento", "Valor", "Juros", "Multa", "Fornecedor" }) {  
  
   public boolean isCellEditable(int row, int col) {  
           return false;  
   
   }});   
      
      gridContaReceber.setModel(  
      new DefaultTableModel(  
      new Object[] []{ },  
      new String[] {"Telefone", "Cliente", "Descricao", "Dt Recebimento", "Dt_Vencimento", "Valor", "Tipo_Pagamento" }) {  
  
   public boolean isCellEditable(int row, int col) {  
           return false;  
   
   }});   
        
        carregaTabelaPagar();
        carregaTabelaReceber();
        carregaFornecedorCombo();
        

       
       // limita campos contas a pagar
       txt_notaPagar.setDocument(new LimitarCampos(50));
       txtfiscal.setDocument(new LimitarCampos(50));
       txt_descricaoPagar.setDocument(new LimitarCampos(200));
       txt_valorPagar.setDocument(new LimitarCampos(10));
       txt_jurosPagar.setDocument(new LimitarCampos(10));
       txt_multaPagar.setDocument(new LimitarCampos(10));
       telefone.setDocument(new LimitarCampos(13));
       
       // limita campos contas a receber
       
       txt_TelefoneClienteReceber.setDocument(new LimitarCampos(9));
       txt_ClienteReceber.setDocument(new LimitarCampos(50));
       txt_descReceber.setDocument(new LimitarCampos(200));
       txt_valorReceber.setDocument(new LimitarCampos(10));
       txt_jurosReceber.setDocument(new LimitarCampos(10));
       txt_multaReceber.setDocument(new LimitarCampos(10));
       
           
       
       
       txt_TelefoneClienteReceber.addFocusListener(new java.awt.event.FocusAdapter() {  
              public void focusLost(java.awt.event.FocusEvent evt) {  
                  txtTelefoneFocusLostCep(evt);  
              }  
              
          });
        
    }
    
    private String combo;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalContasPagarReceber = new javax.swing.JInternalFrame();
        tabContas = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_notaPagar = new Funcoes.ValoresDecimaisPreco(Funcoes.ValoresDecimaisPreco.NotaFiscal);
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_descricaoPagar = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        msk_emissaoPagar = new javax.swing.JFormattedTextField();
        msk_vencimentoPagar = new javax.swing.JFormattedTextField();
        msk_recebimentoPagar = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_valorPagar = new Funcoes.ValoresDecimaisPreco(Funcoes.ValoresDecimaisPreco.REAL);
        txt_jurosPagar = new Funcoes.ValoresDecimaisPreco(Funcoes.ValoresDecimaisPreco.PORCENTAGEM);
        txt_multaPagar = new Funcoes.ValoresDecimaisPreco(Funcoes.ValoresDecimaisPreco.PORCENTAGEM);
        comboFornecedor = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jToolBar2 = new javax.swing.JToolBar();
        btnLimparCamposContaPagar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnGravaContaPagar = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        btnAlterarContaPagar = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        btnExcluirContaPagar = new javax.swing.JButton();
        jSeparator16 = new javax.swing.JToolBar.Separator();
        btnPesquisarContaPagar = new javax.swing.JButton();
        jSeparator14 = new javax.swing.JToolBar.Separator();
        jPanel10 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        gridContasPagar = new javax.swing.JTable();
        txtfiscal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_descReceber = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txt_valorReceber = new Funcoes.ValoresDecimaisPreco(Funcoes.ValoresDecimaisPreco.REAL);
        txt_multaReceber = new Funcoes.ValoresDecimaisPreco(Funcoes.ValoresDecimaisPreco.PORCENTAGEM);
        jButton10 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_jurosReceber = new Funcoes.ValoresDecimaisPreco(Funcoes.ValoresDecimaisPreco.PORCENTAGEM);
        jLabel22 = new javax.swing.JLabel();
        combo_tipoPagamento = new javax.swing.JComboBox();
        combo_parcelas = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txt_dataRecebimento = new javax.swing.JFormattedTextField();
        txt_emissaoReceber = new javax.swing.JFormattedTextField();
        txt_dtRecebimento = new javax.swing.JFormattedTextField();
        jToolBar3 = new javax.swing.JToolBar();
        jButton20 = new javax.swing.JButton();
        jSeparator15 = new javax.swing.JToolBar.Separator();
        jButton21 = new javax.swing.JButton();
        jSeparator17 = new javax.swing.JToolBar.Separator();
        jButton26 = new javax.swing.JButton();
        jSeparator18 = new javax.swing.JToolBar.Separator();
        jButton27 = new javax.swing.JButton();
        jSeparator19 = new javax.swing.JToolBar.Separator();
        jButton28 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_TelefoneClienteReceber = new javax.swing.JTextField();
        txt_ClienteReceber = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        gridContaReceber = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        telefone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        internalContasPagarReceber.setClosable(true);
        internalContasPagarReceber.setTitle("Contas a Pagar e Receber");
        internalContasPagarReceber.setVisible(true);
        internalContasPagarReceber.getContentPane().setLayout(null);

        tabContas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabContasMousePressed(evt);
            }
        });

        jPanel4.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Conta"));
        jPanel2.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Descrição:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 80, 55, 15);

        jLabel1.setText("Nota Fiscal: ");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 40, 80, 14);

        txt_notaPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_notaPagarActionPerformed(evt);
            }
        });
        jPanel2.add(txt_notaPagar);
        txt_notaPagar.setBounds(80, 30, 330, 30);

        txt_descricaoPagar.setColumns(20);
        txt_descricaoPagar.setRows(5);
        jScrollPane1.setViewportView(txt_descricaoPagar);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(80, 80, 330, 80);

        jPanel4.add(jPanel2);
        jPanel2.setBounds(10, 100, 430, 180);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Datas"));
        jPanel5.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Data de Recebimento: ");
        jPanel5.add(jLabel13);
        jLabel13.setBounds(10, 20, 127, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Data de Emissão: ");
        jPanel5.add(jLabel14);
        jLabel14.setBounds(10, 70, 97, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Data de Vencimento:");
        jPanel5.add(jLabel15);
        jLabel15.setBounds(10, 120, 117, 30);

        try {
            msk_emissaoPagar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel5.add(msk_emissaoPagar);
        msk_emissaoPagar.setBounds(140, 70, 80, 30);

        try {
            msk_vencimentoPagar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        msk_vencimentoPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msk_vencimentoPagarActionPerformed(evt);
            }
        });
        jPanel5.add(msk_vencimentoPagar);
        msk_vencimentoPagar.setBounds(140, 120, 80, 30);

        try {
            msk_recebimentoPagar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel5.add(msk_recebimentoPagar);
        msk_recebimentoPagar.setBounds(140, 20, 80, 30);

        jPanel4.add(jPanel5);
        jPanel5.setBounds(470, 100, 350, 180);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalhes"));
        jPanel3.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Valor:");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(18, 46, 44, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Fornecedor: ");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(20, 190, 80, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Juros: ");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(20, 90, 60, 30);
        jPanel3.add(txt_valorPagar);
        txt_valorPagar.setBounds(160, 40, 100, 30);
        jPanel3.add(txt_jurosPagar);
        txt_jurosPagar.setBounds(160, 90, 100, 30);
        jPanel3.add(txt_multaPagar);
        txt_multaPagar.setBounds(160, 140, 100, 30);

        jPanel3.add(comboFornecedor);
        comboFornecedor.setBounds(160, 190, 240, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Multa (% ao dia): ");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(20, 150, 99, 15);

        jPanel4.add(jPanel3);
        jPanel3.setBounds(10, 280, 430, 240);

        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        btnLimparCamposContaPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/novo.png"))); // NOI18N
        btnLimparCamposContaPagar.setText("Limpar Campos");
        btnLimparCamposContaPagar.setFocusable(false);
        btnLimparCamposContaPagar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimparCamposContaPagar.setMargin(new java.awt.Insets(2, 25, 2, 25));
        btnLimparCamposContaPagar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLimparCamposContaPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCamposContaPagarActionPerformed(evt);
            }
        });
        jToolBar2.add(btnLimparCamposContaPagar);
        jToolBar2.add(jSeparator1);

        btnGravaContaPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salvar.png"))); // NOI18N
        btnGravaContaPagar.setText("Gravar");
        btnGravaContaPagar.setFocusable(false);
        btnGravaContaPagar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGravaContaPagar.setMargin(new java.awt.Insets(2, 25, 2, 25));
        btnGravaContaPagar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGravaContaPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravaContaPagarActionPerformed(evt);
            }
        });
        jToolBar2.add(btnGravaContaPagar);
        jToolBar2.add(jSeparator7);

        btnAlterarContaPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/atualizar.png"))); // NOI18N
        btnAlterarContaPagar.setText("Alterar");
        btnAlterarContaPagar.setFocusable(false);
        btnAlterarContaPagar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAlterarContaPagar.setMargin(new java.awt.Insets(2, 25, 2, 25));
        btnAlterarContaPagar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAlterarContaPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarContaPagarActionPerformed(evt);
            }
        });
        jToolBar2.add(btnAlterarContaPagar);
        jToolBar2.add(jSeparator10);

        btnExcluirContaPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/delete.png"))); // NOI18N
        btnExcluirContaPagar.setText("Excluir");
        btnExcluirContaPagar.setFocusable(false);
        btnExcluirContaPagar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluirContaPagar.setMargin(new java.awt.Insets(2, 25, 2, 25));
        btnExcluirContaPagar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExcluirContaPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirContaPagarActionPerformed(evt);
            }
        });
        jToolBar2.add(btnExcluirContaPagar);
        jToolBar2.add(jSeparator16);

        btnPesquisarContaPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/procurar.png"))); // NOI18N
        btnPesquisarContaPagar.setText("Pesquisar");
        btnPesquisarContaPagar.setFocusable(false);
        btnPesquisarContaPagar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPesquisarContaPagar.setMargin(new java.awt.Insets(2, 25, 2, 25));
        btnPesquisarContaPagar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPesquisarContaPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarContaPagarActionPerformed(evt);
            }
        });
        jToolBar2.add(btnPesquisarContaPagar);
        jToolBar2.add(jSeparator14);

        jPanel4.add(jToolBar2);
        jToolBar2.setBounds(0, 0, 750, 80);

        tabContas.addTab("Contas a Pagar", jPanel4);

        jPanel10.setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/procurar.png"))); // NOI18N
        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton1);
        jButton1.setBounds(510, 40, 170, 40);

        gridContasPagar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        gridContasPagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gridContasPagarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                gridContasPagarMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(gridContasPagar);

        jPanel10.add(jScrollPane3);
        jScrollPane3.setBounds(10, 120, 840, 240);
        jPanel10.add(txtfiscal);
        txtfiscal.setBounds(160, 40, 340, 40);

        jLabel5.setText("Nota Fiscal :");
        jPanel10.add(jLabel5);
        jLabel5.setBounds(90, 40, 90, 40);

        tabContas.addTab("Pesquisar Contas a Pagar", jPanel10);

        jPanel6.setLayout(null);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Conta"));
        jPanel7.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Descrição:");
        jPanel7.add(jLabel10);
        jLabel10.setBounds(10, 30, 55, 15);

        txt_descReceber.setColumns(20);
        txt_descReceber.setRows(5);
        jScrollPane2.setViewportView(txt_descReceber);

        jPanel7.add(jScrollPane2);
        jScrollPane2.setBounds(70, 20, 380, 110);

        jPanel6.add(jPanel7);
        jPanel7.setBounds(380, 100, 460, 140);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalhes"));
        jPanel8.setLayout(null);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Tipo de pagamento:");
        jPanel8.add(jLabel17);
        jLabel17.setBounds(10, 180, 130, 15);
        jPanel8.add(txt_valorReceber);
        txt_valorReceber.setBounds(130, 30, 80, 30);
        jPanel8.add(txt_multaReceber);
        txt_multaReceber.setBounds(130, 120, 80, 30);

        jButton10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton10.setText("Pesquisar Conta");
        jPanel8.add(jButton10);
        jButton10.setBounds(530, 520, 160, 50);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Valor:");
        jPanel8.add(jLabel18);
        jLabel18.setBounds(20, 30, 44, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Juros: ");
        jPanel8.add(jLabel11);
        jLabel11.setBounds(20, 80, 60, 30);
        jPanel8.add(txt_jurosReceber);
        txt_jurosReceber.setBounds(130, 80, 80, 30);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("Multa (% ao dia): ");
        jPanel8.add(jLabel22);
        jLabel22.setBounds(10, 125, 99, 30);

        combo_tipoPagamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cartão de Crédito", "Cartão de Débito" }));
        jPanel8.add(combo_tipoPagamento);
        combo_tipoPagamento.setBounds(130, 170, 160, 30);

        combo_parcelas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5" }));
        jPanel8.add(combo_parcelas);
        combo_parcelas.setBounds(130, 210, 40, 30);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Número de parcelas:");
        jPanel8.add(jLabel23);
        jLabel23.setBounds(10, 220, 130, 15);

        jPanel6.add(jPanel8);
        jPanel8.setBounds(380, 260, 460, 270);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Datas"));
        jPanel9.setLayout(null);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Data de Recebimento: ");
        jPanel9.add(jLabel19);
        jLabel19.setBounds(6, 49, 127, 15);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Data de Emissão: ");
        jPanel9.add(jLabel20);
        jLabel20.setBounds(6, 89, 97, 15);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Data de Vencimento:");
        jPanel9.add(jLabel21);
        jLabel21.setBounds(6, 129, 117, 15);

        try {
            txt_dataRecebimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel9.add(txt_dataRecebimento);
        txt_dataRecebimento.setBounds(140, 40, 80, 30);

        try {
            txt_emissaoReceber.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel9.add(txt_emissaoReceber);
        txt_emissaoReceber.setBounds(140, 80, 80, 30);

        try {
            txt_dtRecebimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel9.add(txt_dtRecebimento);
        txt_dtRecebimento.setBounds(140, 120, 80, 30);

        jPanel6.add(jPanel9);
        jPanel9.setBounds(20, 260, 360, 270);

        jToolBar3.setFloatable(false);
        jToolBar3.setRollover(true);

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/novo.png"))); // NOI18N
        jButton20.setText("Limpar Campos");
        jButton20.setFocusable(false);
        jButton20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton20.setMargin(new java.awt.Insets(2, 25, 2, 25));
        jButton20.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jToolBar3.add(jButton20);
        jToolBar3.add(jSeparator15);

        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salvar.png"))); // NOI18N
        jButton21.setText("Gravar");
        jButton21.setFocusable(false);
        jButton21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton21.setMargin(new java.awt.Insets(2, 25, 2, 25));
        jButton21.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jToolBar3.add(jButton21);
        jToolBar3.add(jSeparator17);

        jButton26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/atualizar.png"))); // NOI18N
        jButton26.setText("Alterar");
        jButton26.setFocusable(false);
        jButton26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton26.setMargin(new java.awt.Insets(2, 25, 2, 25));
        jButton26.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        jToolBar3.add(jButton26);
        jToolBar3.add(jSeparator18);

        jButton27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/delete.png"))); // NOI18N
        jButton27.setText("Excluir");
        jButton27.setFocusable(false);
        jButton27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton27.setMargin(new java.awt.Insets(2, 25, 2, 25));
        jButton27.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        jToolBar3.add(jButton27);
        jToolBar3.add(jSeparator19);

        jButton28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/procurar.png"))); // NOI18N
        jButton28.setText("Pesquisar");
        jButton28.setFocusable(false);
        jButton28.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton28.setMargin(new java.awt.Insets(2, 25, 2, 25));
        jButton28.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        jToolBar3.add(jButton28);

        jPanel6.add(jToolBar3);
        jToolBar3.setBounds(0, 0, 850, 80);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));
        jPanel1.setLayout(null);

        jLabel3.setText("Cliente:  ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 60, 60, 30);

        jLabel2.setText("Telefone:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 20, 60, 30);

        txt_TelefoneClienteReceber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_TelefoneClienteReceberFocusLost(evt);
            }
        });
        jPanel1.add(txt_TelefoneClienteReceber);
        txt_TelefoneClienteReceber.setBounds(90, 20, 110, 30);

        txt_ClienteReceber.setEditable(false);
        jPanel1.add(txt_ClienteReceber);
        txt_ClienteReceber.setBounds(30, 90, 310, 30);

        jPanel6.add(jPanel1);
        jPanel1.setBounds(20, 100, 360, 140);

        tabContas.addTab("Contas a Receber", jPanel6);

        jPanel11.setLayout(null);

        gridContaReceber.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        gridContaReceber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gridContaReceberMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(gridContaReceber);

        jPanel11.add(jScrollPane4);
        jScrollPane4.setBounds(10, 140, 840, 240);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/procurar.png"))); // NOI18N
        jButton2.setText("Pesquisar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton2);
        jButton2.setBounds(380, 50, 170, 40);
        jPanel11.add(telefone);
        telefone.setBounds(250, 50, 120, 40);

        jLabel4.setText("Telefone :");
        jPanel11.add(jLabel4);
        jLabel4.setBounds(180, 50, 70, 40);

        tabContas.addTab("Pesquisar Contas a Receber", jPanel11);

        internalContasPagarReceber.getContentPane().add(tabContas);
        tabContas.setBounds(0, 0, 860, 550);

        getContentPane().add(internalContasPagarReceber);
        internalContasPagarReceber.setBounds(10, 10, 890, 580);

        setBounds(0, 0, 921, 634);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirContaPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirContaPagarActionPerformed
        
        

           String  notaFiscal = txt_notaPagar.getText();

            if("0".equals(notaFiscal) || ("").equals(notaFiscal) || "Apenas números".equals(txt_notaPagar)){

                JOptionPane.showMessageDialog(null,"Preencha o campo nota fiscal para realizar uma exclusão");
                txt_notaPagar.requestFocus();

            }

            else{
                if (ba.excluiContaPagar(notaFiscal)) {
                    JOptionPane.showMessageDialog(null, "Excluido com sucesso");
                    
               limparcamposPagar();
                }
                else {
                    JOptionPane.showMessageDialog(null, "Não encontrado");
                }
            }
    }//GEN-LAST:event_btnExcluirContaPagarActionPerformed

    private void btnPesquisarContaPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarContaPagarActionPerformed
        ResultSet rs;
        String notaFiscal = txt_notaPagar.getText();

        if("0".equals(notaFiscal) || ("".equals(notaFiscal) || ("Apenas números".equals(notaFiscal)))){

            JOptionPane.showMessageDialog(null,"Preencha o campo Nota Fiscal para realizar uma busca");
        }

        else{

            rs = ba.buscaContaPagar(notaFiscal);
            try {

                if (ba.buscaContaPagar(notaFiscal) != null) {
                    txt_notaPagar.setText(rs.getString("notaFiscal"));
                    txt_descricaoPagar.setText(rs.getString("descricao"));
                    msk_recebimentoPagar.setText(rs.getString("dataRecebimento"));
                    msk_emissaoPagar.setText(rs.getString("dataEmissao"));
                    msk_vencimentoPagar.setText(rs.getString("dataVencimento"));
                    txt_valorPagar.setText(rs.getString("valor"));
                    txt_jurosPagar.setText(rs.getString("juros"));
                    txt_multaPagar.setText(rs.getString("multa"));

                    
                     String fornecedor = rs.getString("fornecedor");
                  
                    comboFornecedor.setSelectedItem(fornecedor);
                    
                }
                else{

                    JOptionPane.showMessageDialog(rootPane, "não encontrado");

                limparcamposPagar();

                }
            } catch (SQLException ex) {
            }
        }
    }//GEN-LAST:event_btnPesquisarContaPagarActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed

        
         String notaFiscal, descricaoReceber, dtReceber,emissaoReceber, vencimentoReceber,
                 valorReceber,jurosReceber,multaReceber, TelefoneClienteReceber, ClienteReceber, tipopagamento, parcelas;

     
      
        descricaoReceber = txt_descReceber.getText();
        dtReceber = txt_dtRecebimento.getText();
        emissaoReceber = txt_emissaoReceber.getText();
        vencimentoReceber = txt_dataRecebimento.getText();
        valorReceber = txt_valorReceber.getText();
        jurosReceber = txt_jurosReceber.getText();
        multaReceber = txt_multaReceber.getText();
        TelefoneClienteReceber =  txt_TelefoneClienteReceber.getText();
        ClienteReceber  = txt_ClienteReceber.getText();
        tipopagamento = combo_tipoPagamento.getSelectedItem().toString();
        parcelas = combo_parcelas.getSelectedItem().toString();
        
        
        if(TelefoneClienteReceber.equals("") || ClienteReceber.equals("") ){

            JOptionPane.showMessageDialog(null,"Preencha o campo telefone e cliente");
          
        }
        else{
     
            if (ba.gravaContaReceber(descricaoReceber, dtReceber, emissaoReceber, vencimentoReceber, valorReceber, jurosReceber, multaReceber, TelefoneClienteReceber, ClienteReceber, tipopagamento, parcelas)) {
               
                
              limparcamposReceber();
                

            }

        }
        
    }//GEN-LAST:event_jButton21ActionPerformed

    public void limparcamposReceber(){
        
                txt_TelefoneClienteReceber.setText("");
                txt_ClienteReceber.setText("");
                txt_dataRecebimento.setText("");
                txt_emissaoReceber.setText("");
                txt_dtRecebimento.setText("");
                txt_descReceber.setText("");
                txt_valorReceber.setText("0");
                txt_jurosReceber.setText("0");
                txt_multaReceber.setText("0");
              
        
    }
    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        
        
         ResultSet rs;
        String telefone = txt_TelefoneClienteReceber.getText();

        if("".equals(telefone)){

            JOptionPane.showMessageDialog(null,"Preencha o campo telefone para realizar uma busca");
        }

        else{

            rs = ba.buscaContaReceber(telefone);
            try {

                if (ba.buscaContaReceber(telefone) != null) {
                    
                    txt_ClienteReceber.setText(rs.getString("cliente"));
                    txt_dataRecebimento.setText(rs.getString("dtrecebimento"));
                    txt_emissaoReceber.setText(rs.getString("dtemissao"));
                    txt_dtRecebimento.setText(rs.getString("dtvencimento"));
                    txt_descReceber.setText(rs.getString("descricao"));
                    txt_valorReceber.setText(rs.getString("valor"));
                    txt_jurosReceber.setText(rs.getString("juros"));
                    txt_multaReceber.setText(rs.getString("multa"));
                    

                    
                     String tipopagamento = rs.getString("tipopagamento");
                     String parcelas = rs.getString("nparcela");
                  
                    combo_tipoPagamento.setSelectedItem(tipopagamento);
                    
                    combo_parcelas.setSelectedItem(parcelas);
                    
                }
                else{

                    JOptionPane.showMessageDialog(rootPane, "não encontrado");

               limparcamposReceber();

                }
            } catch (SQLException ex) {
            }
        }
    }//GEN-LAST:event_jButton28ActionPerformed

    private void btnGravaContaPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravaContaPagarActionPerformed
        String notaFiscal, descricao, recebimento,emissao, vencimento, valor,juros,multa, fornecedor;

        notaFiscal = txt_notaPagar.getText();
        descricao = txt_descricaoPagar.getText();
        recebimento = msk_recebimentoPagar.getText();
        emissao = msk_emissaoPagar.getText();
        vencimento = msk_vencimentoPagar.getText();
        valor = txt_valorPagar.getText();
        juros = txt_jurosPagar.getText();
        multa = txt_multaPagar.getText();
        
       fornecedor = comboFornecedor.getSelectedItem().toString();
        

        if("".equals(notaFiscal) || "0".equals(notaFiscal) || "".equals(descricao) || "  /  /    ".equals(descricao)
            || "  /  /    ".equals(recebimento) || "  /  /    ".equals(emissao)
            || "  /  /    ".equals(vencimento) || "".equals(valor) || "".equals(juros) || "".equals(multa)
            || "Apenas números".equals(txt_notaPagar) || "Apenas números".equals(txt_valorPagar) || "Apenas números".equals(txt_multaPagar) ){

            JOptionPane.showMessageDialog(null,"Preencha os campos corretamente");
          
        }
        else{
           

            if (ba.gravaContaPagar(notaFiscal, descricao, recebimento,emissao, vencimento, valor,juros,multa, fornecedor)) {

                limparcamposPagar();
                

            }

        }
    }//GEN-LAST:event_btnGravaContaPagarActionPerformed

    private void btnLimparCamposContaPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCamposContaPagarActionPerformed

              limparcamposPagar();
    }//GEN-LAST:event_btnLimparCamposContaPagarActionPerformed

    public void limparcamposPagar(){
        
        txt_notaPagar.setText("0");
                txt_descricaoPagar.setText("");
                msk_recebimentoPagar.setText("");
                msk_emissaoPagar.setText("");
                msk_vencimentoPagar.setText("");
                txt_valorPagar.setText("0");
                txt_jurosPagar.setText("0");
                txt_multaPagar.setText("0");
        
    }
    private void btnAlterarContaPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarContaPagarActionPerformed

           
        String notaFiscal, descricao, recebimento,emissao, vencimento, valor,juros,multa, fornecedor;
        
        notaFiscal = txt_notaPagar.getText();
        descricao = txt_descricaoPagar.getText();
        recebimento = msk_recebimentoPagar.getText();
        emissao = msk_emissaoPagar.getText();
        vencimento = msk_vencimentoPagar.getText();
        valor = txt_valorPagar.getText();
        juros = txt_jurosPagar.getText();
        multa = txt_multaPagar.getText();
        
        fornecedor = comboFornecedor.getSelectedItem().toString();


        if("".equals(notaFiscal)||"0".equals(notaFiscal) ){

            JOptionPane.showMessageDialog(null,"Preecha o campo nota fiscal");
            txt_notaPagar.requestFocus();
        }
        else{

            ba.atualizaContaPagar(notaFiscal, descricao, recebimento,emissao, vencimento, valor,juros,multa, fornecedor);

        }
        
    }//GEN-LAST:event_btnAlterarContaPagarActionPerformed

    private void txtTelefoneFocusLostCep(java.awt.event.FocusEvent evt) {  
        ResultSet rs;
   

        String telefone = txt_TelefoneClienteReceber.getText();

        if("".equals(telefone)){

        }

        
        else{
            
            
            rs = ba.buscaCliente(telefone);
            try {

                if (ba.buscaCliente(telefone) != null) {

                    txt_ClienteReceber.setText(rs.getString("nome"));
                   
                }
                else{

                }
            } catch (SQLException ex) {
            }
        } 
    }
    
    private void txt_notaPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_notaPagarActionPerformed


    }//GEN-LAST:event_txt_notaPagarActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        
       
        
           String  telefone = txt_TelefoneClienteReceber.getText();

            if( "".equals(txt_TelefoneClienteReceber)){

                JOptionPane.showMessageDialog(null,"Preencha o campo telefone para realizar uma exclusão");
                txt_TelefoneClienteReceber.requestFocus();

            }

            else{
                if (ba.excluiContaReceber(telefone)) {
                    JOptionPane.showMessageDialog(null, "Excluido com sucesso");
                    
               limparcamposReceber();
                }
                else {
                    JOptionPane.showMessageDialog(null, "Não encontrado");
                }
            }
        
    }//GEN-LAST:event_jButton27ActionPerformed

    private void msk_vencimentoPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msk_vencimentoPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msk_vencimentoPagarActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed

        
         String descricaoReceber, dtReceber,emissaoReceber, vencimentoReceber,
                 valorReceber,jurosReceber,multaReceber, TelefoneClienteReceber, ClienteReceber, tipopagamento, parcelas;

     
        descricaoReceber = txt_descReceber.getText();
        dtReceber = txt_dtRecebimento.getText();
        emissaoReceber = txt_emissaoReceber.getText();
        vencimentoReceber = txt_dataRecebimento.getText();
        valorReceber = txt_valorReceber.getText();
        jurosReceber = txt_jurosReceber.getText();
        multaReceber = txt_multaReceber.getText();
        TelefoneClienteReceber =  txt_TelefoneClienteReceber.getText();
        ClienteReceber  = txt_ClienteReceber.getText();
        tipopagamento = combo_tipoPagamento.getSelectedItem().toString();
        parcelas = combo_parcelas.getSelectedItem().toString();
        

        if("".equals(TelefoneClienteReceber) ){

            JOptionPane.showMessageDialog(null,"Preecha o campo telefone");
            txt_notaPagar.requestFocus();
        }
        else{

            ba.atualizaContaReceber( descricaoReceber, dtReceber,emissaoReceber, vencimentoReceber,
                 valorReceber,jurosReceber,multaReceber, TelefoneClienteReceber, ClienteReceber, tipopagamento, parcelas);

        }

    }//GEN-LAST:event_jButton26ActionPerformed

     
    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        limparcamposReceber();
    }//GEN-LAST:event_jButton20ActionPerformed

    private void txt_TelefoneClienteReceberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_TelefoneClienteReceberFocusLost
        
        
        
        
    }//GEN-LAST:event_txt_TelefoneClienteReceberFocusLost

    private void gridContasPagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gridContasPagarMouseClicked
         // PEGA OS CAMPOS QUE ESTÃO NA JTABLE 
        
        if (evt.getClickCount() == 2) {  
            
            Object obj = (gridContasPagar.getValueAt(gridContasPagar.getSelectedRow(), 0));  //coluna 0  
            String notaFiscal = obj.toString();
            
     ResultSet rs;
       

      

      

            rs = ba.buscaContaPagar(notaFiscal);
            try {

                if (ba.buscaContaPagar(notaFiscal) != null) {
                    
                    txt_notaPagar.setText(notaFiscal);
                    txt_notaPagar.setText(rs.getString("notaFiscal"));
                    txt_descricaoPagar.setText(rs.getString("descricao"));
                    msk_recebimentoPagar.setText(rs.getString("dataRecebimento"));
                    msk_emissaoPagar.setText(rs.getString("dataEmissao"));
                    msk_vencimentoPagar.setText(rs.getString("dataVencimento"));
                    txt_valorPagar.setText(rs.getString("valor"));
                    txt_jurosPagar.setText(rs.getString("juros"));
                    txt_multaPagar.setText(rs.getString("multa"));

                    
                     String fornecedor = rs.getString("fornecedor");
                  
                    comboFornecedor.setSelectedItem(fornecedor);
                    
                }
                else{

                    JOptionPane.showMessageDialog(rootPane, "não encontrado");

                limparcamposPagar();

                }
            } catch (SQLException ex) {
            }
        
             
             
             
               // QUANDO SELECIONA A LINHA NA JTABLE MUDA A ABA
              tabContas.setSelectedIndex(0);   
             
              
        }  
    }//GEN-LAST:event_gridContasPagarMouseClicked

    private void gridContasPagarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gridContasPagarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_gridContasPagarMousePressed

    private void tabContasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabContasMousePressed
       carregaTabelaPagar();
       carregaTabelaReceber();
    }//GEN-LAST:event_tabContasMousePressed

    private void gridContaReceberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gridContaReceberMouseClicked
        if (evt.getClickCount() == 2) {  
        
        Object obj = (gridContaReceber.getValueAt(gridContaReceber.getSelectedRow(), 0));  //coluna 0  
            String telefone = obj.toString();
            
         ResultSet rs;
     

        if("".equals(telefone)){

            JOptionPane.showMessageDialog(null,"Preencha o campo telefone para realizar uma busca");
        }

        else{

            rs = ba.buscaContaReceber(telefone);
            try {

                if (ba.buscaContaReceber(telefone) != null) {
                    
                    txt_TelefoneClienteReceber.setText(telefone);
                    txt_ClienteReceber.setText(rs.getString("cliente"));
                    txt_dataRecebimento.setText(rs.getString("dtrecebimento"));
                    txt_emissaoReceber.setText(rs.getString("dtemissao"));
                    txt_dtRecebimento.setText(rs.getString("dtvencimento"));
                    txt_descReceber.setText(rs.getString("descricao"));
                    txt_valorReceber.setText(rs.getString("valor"));
                    txt_jurosReceber.setText(rs.getString("juros"));
                    txt_multaReceber.setText(rs.getString("multa"));
                    

                    
                     String tipopagamento = rs.getString("tipopagamento");
                     String parcelas = rs.getString("nparcela");
                  
                    combo_tipoPagamento.setSelectedItem(tipopagamento);
                    
                    combo_parcelas.setSelectedItem(parcelas);
                    
                }
                else{

                    JOptionPane.showMessageDialog(rootPane, "não encontrado");

               limparcamposReceber();

                }
            } catch (SQLException ex) {
            }
        }
         tabContas.setSelectedIndex(2);   
        }
    }//GEN-LAST:event_gridContaReceberMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String cod = txtfiscal.getText();
       
       if(cod.equals("")){
           
           
            JOptionPane.showMessageDialog(null,"Insira o codigo da nota fiscal");
           
       }
       else {
       
         String msg1 = "Clientes recuperados com sucesso";
        String msg2 = "Erro ao Recuperar Clientes";
        String vsql = "SELECT * from contaspagar where notaFiscal = "+cod+"";


        bf.tabelaContasPagar(vsql, msg1, msg2, gridContasPagar);
        
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
         String tel = telefone.getText();
       
       if(tel.equals("")){
           
           
            JOptionPane.showMessageDialog(null,"Insira o telefone");
           
       }
       else {
       
         String msg1 = "Clientes recuperados com sucesso";
        String msg2 = "Erro ao Recuperar Clientes";
        String vsql = "SELECT * from contasreceber where telefone = "+tel+"";


       bf.tabelaContasReceber(vsql, msg1, msg2, gridContaReceber);
        
       }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContasPagarReceber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContasPagarReceber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContasPagarReceber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContasPagarReceber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContasPagarReceber().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarContaPagar;
    private javax.swing.JButton btnExcluirContaPagar;
    private javax.swing.JButton btnGravaContaPagar;
    private javax.swing.JButton btnLimparCamposContaPagar;
    private javax.swing.JButton btnPesquisarContaPagar;
    private javax.swing.JComboBox comboFornecedor;
    private javax.swing.JComboBox combo_parcelas;
    private javax.swing.JComboBox combo_tipoPagamento;
    private javax.swing.JTable gridContaReceber;
    private javax.swing.JTable gridContasPagar;
    public javax.swing.JInternalFrame internalContasPagarReceber;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator14;
    private javax.swing.JToolBar.Separator jSeparator15;
    private javax.swing.JToolBar.Separator jSeparator16;
    private javax.swing.JToolBar.Separator jSeparator17;
    private javax.swing.JToolBar.Separator jSeparator18;
    private javax.swing.JToolBar.Separator jSeparator19;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JFormattedTextField msk_emissaoPagar;
    private javax.swing.JFormattedTextField msk_recebimentoPagar;
    private javax.swing.JFormattedTextField msk_vencimentoPagar;
    private javax.swing.JTabbedPane tabContas;
    private javax.swing.JTextField telefone;
    private javax.swing.JTextField txt_ClienteReceber;
    private javax.swing.JTextField txt_TelefoneClienteReceber;
    private javax.swing.JFormattedTextField txt_dataRecebimento;
    private javax.swing.JTextArea txt_descReceber;
    private javax.swing.JTextArea txt_descricaoPagar;
    private javax.swing.JFormattedTextField txt_dtRecebimento;
    private javax.swing.JFormattedTextField txt_emissaoReceber;
    private javax.swing.JFormattedTextField txt_jurosPagar;
    private javax.swing.JTextField txt_jurosReceber;
    private javax.swing.JFormattedTextField txt_multaPagar;
    private javax.swing.JTextField txt_multaReceber;
    private javax.swing.JFormattedTextField txt_notaPagar;
    private javax.swing.JFormattedTextField txt_valorPagar;
    private javax.swing.JTextField txt_valorReceber;
    private javax.swing.JTextField txtfiscal;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the combo
     */
    public String getCombo() {
         return combo = (String) comboFornecedor.getSelectedItem();
    }

    /**
     * @param combo the combo to set
     */
    public void setCombo(String combo) {
        this.combo = combo;
    }
    
    public void carregaFornecedorCombo(){
        String msg1 = "Fornecedores recuperados";
        String msg2 = "Erro ao Recuperar Fornecedores";
        String vsql = "SELECT nomeFantasia FROM fornecedor order by nomeFantasia";
        String campoSql = "nomeFantasia";

        bf.carregaDadoUnico(vsql, msg1, msg2, comboFornecedor, campoSql);
    }
    
    public void carregaTabelaPagar(){
        String msg1 = "Clientes recuperados com sucesso";
        String msg2 = "Erro ao Recuperar Clientes";
        String vsql = "SELECT * from contaspagar";


        bf.tabelaContasPagar(vsql, msg1, msg2, gridContasPagar);
    }
    
    public void carregaTabelaReceber(){
        String msg1 = "Conta recuperados com sucesso";
        String msg2 = "Erro ao Recuperar Conta";
        String vsql = "SELECT * from contasreceber";


        bf.tabelaContasReceber(vsql, msg1, msg2, gridContaReceber);
    }
}
