/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fornecedor;
import Banco.Banco;
import Banco.BancoCep;
import Banco.BancoFuncoes;
import BancoObjeto.ObjetoFornecedor;
import BancoObjeto.ObjetoFuncionario;
import Funcoes.LimitarCampos;
import Funcoes.ValidaCnpj;
import static Funcoes.ValoresDecimaisPreco.CNPJ;
import org.alfredlibrary.formatadores.CEP;
import org.alfredlibrary.validadores.CPF;
import org.alfredlibrary.validadores.CNPJ;
import org.alfredlibrary.validadores.Email;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static org.alfredlibrary.validadores.CNPJ.isValido;

/**
 *
 * @author Paulo
 */
public class Fornecedor extends javax.swing.JPanel {

    Banco ba = new Banco();
    BancoFuncoes bf = new BancoFuncoes();
    String tipoPessoa;
    private String combo;
    
    public Fornecedor() {
        initComponents();
        carregaTipoPruduto();
        
        // CRIA O TABLE MODEL DO gridFornecedor 
        
      gridFornecedor.setModel(  
      new DefaultTableModel(  
      new Object[] []{ },  
      new String[] {"Nome", "CNPJ_CPF","Inc_Est","Tipo", "Nome Contato", "Telefone", "Celular"
              , "UF", "Email" ,"Tipo_Produto" }) {  
  
          // BLOQUEIA A EDIÇÃO DA JTABLE
          
   public boolean isCellEditable(int row, int col) {  
           return false;  
   
   }});   
        
      carregaTabela();
        
          labelCpf.setVisible(false);
          txt_cpfFor.setVisible(false);
           AlertaCnpj.setVisible(false);
           
           
           labelCpfPesquisa.setVisible(false);
           txt_CpfPesquisa.setVisible(false);
  
        
        String cnpjFor =txt_cnpjFor2.getText();
        int test;
        
        
        
        
        nome_fantasiaFor.setDocument(new LimitarCampos(50));
        txt_cepFor.setDocument(new LimitarCampos(8));
        txt_cidadeFor.setDocument(new LimitarCampos(30));
        txt_bairroFor.setDocument(new LimitarCampos(30));
        txt_endeFor.setDocument(new LimitarCampos(50));
        txt_numFor.setDocument(new LimitarCampos(5));
        nome_contatoFor.setDocument(new LimitarCampos(40));
        txt_emailFor.setDocument(new LimitarCampos(40));
        txt_siteFor.setDocument(new LimitarCampos(50));
        txt_estadoFor.setDocument(new LimitarCampos(2));
  
        
        
        
        
         txt_cepFor.addFocusListener(new java.awt.event.FocusAdapter() {  
              public void focusLost(java.awt.event.FocusEvent evt) {  
                  jTextField1FocusLostCep(evt);  
              }  
          });  
         
         txt_cnpjFor2.addFocusListener(new java.awt.event.FocusAdapter() {  
              public void focusLost(java.awt.event.FocusEvent evt) {  
                  jTextField1FocusLostCnpj(evt);  
              }  
          });
         
         txt_emailFor.addFocusListener(new java.awt.event.FocusAdapter() {  
              public void focusLost(java.awt.event.FocusEvent evt) {  
                  jTextField1FocusLostEmail(evt);  
              }  
          });
         
         txt_cpfFor.addFocusListener(new java.awt.event.FocusAdapter() {  
              public void focusLost(java.awt.event.FocusEvent evt) {  
                  jTextField1FocusLostCpf(evt);  
              }  
          });
         
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
     BancoCep bacep = new BancoCep();
     

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoRadio = new javax.swing.ButtonGroup();
        grupoRadioPesquisa = new javax.swing.ButtonGroup();
        jMenuItem1 = new javax.swing.JMenuItem();
        internalFornecedor = new javax.swing.JInternalFrame();
        TabFornecedor = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        Pesquisar = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        Gravar = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        Alterar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        Excluir = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        Novo = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jPanel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_estadoFor = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txt_cidadeFor = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_bairroFor = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txt_endeFor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_numFor = new javax.swing.JTextField();
        txt_cepFor = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        nome_contatoFor = new javax.swing.JTextField();
        txt_telFor = new javax.swing.JFormattedTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txt_tel2For = new javax.swing.JFormattedTextField();
        txt_emailFor = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_celFor = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_siteFor = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        labelCnpj = new javax.swing.JLabel();
        labelEstadual = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_cnpjFor2 = new javax.swing.JFormattedTextField();
        nome_fantasiaFor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboTipoProduto = new javax.swing.JComboBox();
        pessoaFisica = new javax.swing.JRadioButton();
        pessoaJuridica = new javax.swing.JRadioButton();
        txt_estadualFor = new javax.swing.JFormattedTextField();
        labelCpf = new javax.swing.JLabel();
        txt_cpfFor = new javax.swing.JFormattedTextField();
        AlertaCnpj = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelCpfPesquisa = new javax.swing.JLabel();
        txt_CpfPesquisa = new javax.swing.JFormattedTextField();
        radioFisicaPesquisa = new javax.swing.JRadioButton();
        radioJuridicaPesquisa = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        gridFornecedor = new javax.swing.JTable();
        txt_CnpjPesquisa = new javax.swing.JFormattedTextField();
        labelCnpjPesquisa = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setLayout(null);

        internalFornecedor.setClosable(true);
        internalFornecedor.setResizable(true);
        internalFornecedor.setTitle("Fornecedor");
        internalFornecedor.setVisible(true);
        internalFornecedor.getContentPane().setLayout(null);

        TabFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TabFornecedorMousePressed(evt);
            }
        });

        jPanel2.setLayout(null);

        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        Pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/procurar.png"))); // NOI18N
        Pesquisar.setText("Consultar");
        Pesquisar.setFocusable(false);
        Pesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Pesquisar.setMargin(new java.awt.Insets(2, 25, 2, 25));
        Pesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarActionPerformed(evt);
            }
        });
        jToolBar2.add(Pesquisar);
        jToolBar2.add(jSeparator8);

        Gravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salvar.png"))); // NOI18N
        Gravar.setText("Inserir");
        Gravar.setFocusable(false);
        Gravar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Gravar.setMargin(new java.awt.Insets(2, 25, 2, 25));
        Gravar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Gravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GravarActionPerformed(evt);
            }
        });
        jToolBar2.add(Gravar);
        jToolBar2.add(jSeparator7);

        Alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/atualizar.png"))); // NOI18N
        Alterar.setText("Alterar");
        Alterar.setFocusable(false);
        Alterar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Alterar.setMargin(new java.awt.Insets(2, 25, 2, 25));
        Alterar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarActionPerformed(evt);
            }
        });
        jToolBar2.add(Alterar);
        jToolBar2.add(jSeparator4);

        Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/delete.png"))); // NOI18N
        Excluir.setText("Excluir");
        Excluir.setFocusable(false);
        Excluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Excluir.setMargin(new java.awt.Insets(2, 25, 2, 25));
        Excluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });
        jToolBar2.add(Excluir);
        jToolBar2.add(jSeparator6);

        Novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/novo.png"))); // NOI18N
        Novo.setText("Limpar Campos");
        Novo.setFocusable(false);
        Novo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Novo.setMargin(new java.awt.Insets(2, 25, 2, 25));
        Novo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoActionPerformed(evt);
            }
        });
        jToolBar2.add(Novo);
        jToolBar2.add(jSeparator3);

        jPanel2.add(jToolBar2);
        jToolBar2.setBounds(0, 0, 1260, 80);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));
        jPanel4.setLayout(null);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setText("CEP:");
        jPanel4.add(jLabel20);
        jLabel20.setBounds(20, 20, 60, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Estado: *");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(250, 20, 80, 30);
        jPanel4.add(txt_estadoFor);
        txt_estadoFor.setBounds(330, 20, 40, 30);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 51));
        jLabel26.setText("Cidade:");
        jPanel4.add(jLabel26);
        jLabel26.setBounds(410, 20, 70, 30);
        jPanel4.add(txt_cidadeFor);
        txt_cidadeFor.setBounds(490, 20, 290, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Bairro:");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(20, 60, 80, 30);
        jPanel4.add(txt_bairroFor);
        txt_bairroFor.setBounds(110, 60, 260, 30);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("Endereço:");
        jPanel4.add(jLabel22);
        jLabel22.setBounds(20, 100, 80, 30);
        jPanel4.add(txt_endeFor);
        txt_endeFor.setBounds(110, 100, 410, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Número:");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(550, 100, 70, 30);
        jPanel4.add(txt_numFor);
        txt_numFor.setBounds(620, 100, 60, 30);
        jPanel4.add(txt_cepFor);
        txt_cepFor.setBounds(110, 20, 110, 30);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(0, 250, 940, 140);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Contato"));
        jPanel5.setLayout(null);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setText("Nome Contato:");
        jPanel5.add(jLabel21);
        jLabel21.setBounds(10, 20, 120, 30);
        jPanel5.add(nome_contatoFor);
        nome_contatoFor.setBounds(110, 20, 340, 30);

        try {
            txt_telFor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel5.add(txt_telFor);
        txt_telFor.setBounds(110, 60, 150, 30);

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setText("Telefone:");
        jPanel5.add(jLabel29);
        jLabel29.setBounds(40, 60, 80, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("WebSite:");
        jPanel5.add(jLabel3);
        jLabel3.setBounds(50, 100, 70, 30);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setText("Telefone 2:");
        jPanel5.add(jLabel25);
        jLabel25.setBounds(270, 60, 80, 30);

        try {
            txt_tel2For.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_tel2For.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tel2ForActionPerformed(evt);
            }
        });
        jPanel5.add(txt_tel2For);
        txt_tel2For.setBounds(350, 60, 170, 30);

        txt_emailFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailForActionPerformed(evt);
            }
        });
        jPanel5.add(txt_emailFor);
        txt_emailFor.setBounds(510, 20, 280, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("Celular:");
        jPanel5.add(jLabel18);
        jLabel18.setBounds(540, 60, 60, 30);

        try {
            txt_celFor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel5.add(txt_celFor);
        txt_celFor.setBounds(610, 60, 150, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Email:");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(470, 20, 50, 30);
        jPanel5.add(txt_siteFor);
        txt_siteFor.setBounds(110, 100, 420, 30);

        jPanel2.add(jPanel5);
        jPanel5.setBounds(0, 390, 940, 150);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));
        jPanel3.setLayout(null);

        labelCnpj.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelCnpj.setForeground(new java.awt.Color(51, 51, 51));
        labelCnpj.setText("CNPJ:*");
        jPanel3.add(labelCnpj);
        labelCnpj.setBounds(20, 70, 50, 30);

        labelEstadual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelEstadual.setText("Inscri.Estadual:");
        jPanel3.add(labelEstadual);
        labelEstadual.setBounds(260, 70, 120, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Nome :");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(10, 110, 120, 30);

        try {
            txt_cnpjFor2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_cnpjFor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cnpjFor2ActionPerformed(evt);
            }
        });
        jPanel3.add(txt_cnpjFor2);
        txt_cnpjFor2.setBounds(120, 70, 130, 30);
        jPanel3.add(nome_fantasiaFor);
        nome_fantasiaFor.setBounds(120, 110, 390, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Tipo de produtos:");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(560, 110, 120, 30);

        comboTipoProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(comboTipoProduto);
        comboTipoProduto.setBounds(700, 110, 150, 30);

        grupoRadio.add(pessoaFisica);
        pessoaFisica.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pessoaFisica.setText("Pessoa Fisica");
        pessoaFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pessoaFisicaActionPerformed(evt);
            }
        });
        jPanel3.add(pessoaFisica);
        pessoaFisica.setBounds(10, 30, 103, 25);

        grupoRadio.add(pessoaJuridica);
        pessoaJuridica.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pessoaJuridica.setText("Pessoa Jurídica");
        pessoaJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pessoaJuridicaActionPerformed(evt);
            }
        });
        jPanel3.add(pessoaJuridica);
        pessoaJuridica.setBounds(140, 30, 120, 25);

        try {
            txt_estadualFor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel3.add(txt_estadualFor);
        txt_estadualFor.setBounds(380, 70, 140, 30);

        labelCpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelCpf.setText("CPF: ");
        jPanel3.add(labelCpf);
        labelCpf.setBounds(20, 70, 40, 30);

        try {
            txt_cpfFor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_cpfFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cpfForActionPerformed(evt);
            }
        });
        jPanel3.add(txt_cpfFor);
        txt_cpfFor.setBounds(120, 70, 130, 30);

        AlertaCnpj.setBackground(new java.awt.Color(255, 51, 51));
        AlertaCnpj.setOpaque(true);
        jPanel3.add(AlertaCnpj);
        AlertaCnpj.setBounds(10, 70, 220, 30);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 90, 940, 160);

        TabFornecedor.addTab("Registrar Fornecedor", jPanel2);

        jPanel1.setLayout(null);

        labelCpfPesquisa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelCpfPesquisa.setText("CPF:");
        jPanel1.add(labelCpfPesquisa);
        labelCpfPesquisa.setBounds(280, 70, 40, 40);

        try {
            txt_CpfPesquisa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_CpfPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CpfPesquisaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_CpfPesquisa);
        txt_CpfPesquisa.setBounds(320, 70, 140, 40);

        grupoRadioPesquisa.add(radioFisicaPesquisa);
        radioFisicaPesquisa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioFisicaPesquisa.setText("Pessoa Fisica");
        radioFisicaPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioFisicaPesquisaActionPerformed(evt);
            }
        });
        jPanel1.add(radioFisicaPesquisa);
        radioFisicaPesquisa.setBounds(310, 20, 130, 25);

        grupoRadioPesquisa.add(radioJuridicaPesquisa);
        radioJuridicaPesquisa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioJuridicaPesquisa.setText("Pessoa Juridica");
        radioJuridicaPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioJuridicaPesquisaActionPerformed(evt);
            }
        });
        jPanel1.add(radioJuridicaPesquisa);
        radioJuridicaPesquisa.setBounds(480, 20, 130, 25);

        gridFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        gridFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gridFornecedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(gridFornecedor);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 140, 930, 400);

        try {
            txt_CnpjPesquisa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_CnpjPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CnpjPesquisaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_CnpjPesquisa);
        txt_CnpjPesquisa.setBounds(320, 70, 140, 40);

        labelCnpjPesquisa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelCnpjPesquisa.setText("CNPJ:");
        jPanel1.add(labelCnpjPesquisa);
        labelCnpjPesquisa.setBounds(280, 70, 40, 40);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/procurar.png"))); // NOI18N
        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(490, 70, 140, 40);

        TabFornecedor.addTab("Pesquisar Fornecedor", jPanel1);

        internalFornecedor.getContentPane().add(TabFornecedor);
        TabFornecedor.setBounds(0, 0, 960, 580);

        add(internalFornecedor);
        internalFornecedor.setBounds(30, 20, 980, 610);
    }// </editor-fold>//GEN-END:initComponents

    private void NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoActionPerformed

        AlertaCnpj.setVisible(false);

       limpacampos();
    }//GEN-LAST:event_NovoActionPerformed

    private void GravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GravarActionPerformed

        
     /*SE A PESSOA FOR FISICA FAZ A INSERÇÃO NO BANCO É O MESMO CODIGO DE BAIXO*/
        
        
               
        if(pessoaFisica.isSelected()){
        
           String tipoPessoa = "Pessoa Fisica";   
        
             AlertaCnpj.setVisible(false);

        String nomeFantasia, endeFor, cidadeFor, nomeContato, emailFor, bairroFor,cnpjFor, cepFor, telFor, celFor, estadualFor, numFor, tel2For, siteFor,cpfFor, ufFor,tipoproduto;

        ufFor = txt_estadoFor.getText();
        cpfFor = txt_cpfFor.getText();
        nomeFantasia = nome_fantasiaFor.getText();
        cnpjFor = txt_cnpjFor2.getText();
        endeFor = txt_endeFor.getText();
        cidadeFor = txt_cidadeFor.getText();
        nomeContato = nome_contatoFor.getText();
        emailFor = txt_emailFor.getText();
        bairroFor = txt_bairroFor.getText();
        telFor = txt_telFor.getText();
        cepFor = txt_cepFor.getText();
        estadualFor = txt_estadualFor.getText();
        celFor = txt_celFor.getText();
        numFor = txt_numFor.getText();
        tel2For = txt_tel2For.getText();
        siteFor = txt_siteFor.getText();
        tipoproduto = comboTipoProduto.getSelectedItem().toString();
      
       if(CPF.isValido(cpfFor) == false || "111.111.111-11".equals(cpfFor)  || "00.000.000-00".equals(cpfFor) || "  .   .   -  ".equals(cpfFor)){

            JOptionPane.showMessageDialog(null,"CPF Inválido");
            AlertaCnpj.setVisible(true);
            txt_cnpjFor2.requestFocus();
            
        }
       
       else{
            ba.gravaFornecedor(nomeFantasia, endeFor, cidadeFor, nomeContato, emailFor, bairroFor,cnpjFor,
                    cepFor, telFor, celFor, estadualFor, numFor, tel2For, siteFor, tipoPessoa, cpfFor, ufFor, tipoproduto);

           limpacampos();
        }
       
        }
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        /*SE A PESSOA FOR JURIDICA FAZ A INSERÇÃO NO BANCO É O MESMO CODIGO DE CIMA*/
        
        
        else if(pessoaJuridica.isSelected()){
        
        String tipoPessoa = "Pessoa Juridica";
        
        
          AlertaCnpj.setVisible(false);

        String nomeFantasia, endeFor, cidadeFor, nomeContato, emailFor, bairroFor,cnpjFor, cepFor, telFor, celFor, estadualFor, numFor, tel2For, siteFor, cpfFor, ufFor,tipoproduto;

        ufFor = txt_estadoFor.getText();
        cpfFor = txt_cpfFor.getText();
        cnpjFor = txt_cnpjFor2.getText();
        nomeFantasia = nome_fantasiaFor.getText();
        cnpjFor = txt_cnpjFor2.getText();
        endeFor = txt_endeFor.getText();
        cidadeFor = txt_cidadeFor.getText();
        nomeContato = nome_contatoFor.getText();
        emailFor = txt_emailFor.getText();
        bairroFor = txt_bairroFor.getText();
        telFor = txt_telFor.getText();
        cepFor = txt_cepFor.getText();
        estadualFor = txt_estadualFor.getText();
        celFor = txt_celFor.getText();
        numFor = txt_numFor.getText();
        tel2For = txt_tel2For.getText();
        siteFor = txt_siteFor.getText();
        tipoproduto = comboTipoProduto.getSelectedItem().toString();
      
       if(isValido(cnpjFor) == false || "11.111.111/1111-11".equals(cnpjFor) || "  .   .   /    -  ".equals(cnpjFor) || "00.000.000/0000-00".equals(cnpjFor)){

            JOptionPane.showMessageDialog(null,"CNPJ Inválido");
            AlertaCnpj.setVisible(true);
            txt_cnpjFor2.requestFocus();
            
        }
       
        else{
            ba.gravaFornecedor(nomeFantasia, endeFor, cidadeFor, nomeContato, emailFor, bairroFor,cnpjFor, cepFor, telFor, celFor, estadualFor, numFor, tel2For, siteFor, tipoPessoa,cpfFor, ufFor, tipoproduto);

           limpacampos();
        }
        
    }
        
        else{
        
         JOptionPane.showMessageDialog(null,"Atenção selecione se a pessoa é fisica ou juridica ");
        
        }
        
        
    

    }//GEN-LAST:event_GravarActionPerformed

    public void limpacampos(){
        txt_cpfFor.setText("");
            nome_fantasiaFor.setText("");
            txt_cnpjFor2.setText("");
            txt_endeFor.setText("");
            txt_cidadeFor.setText("");
            nome_contatoFor.setText("");
            txt_emailFor.setText("");
            txt_bairroFor.setText("");
            txt_telFor.setText("");
            txt_cepFor.setText("");
            txt_estadualFor.setText("");
            txt_celFor.setText("");
            txt_numFor.setText("");
            txt_tel2For.setText("");
            txt_siteFor.setText("");
            txt_estadoFor.setText("");
            comboTipoProduto.setSelectedItem("");
            AlertaCnpj.setVisible(false);
    }
    
    private void AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarActionPerformed
  String nomeFantasia, endeFor, cidadeFor, nomeContato, emailFor, bairroFor,cnpjFor, cepFor, telFor, celFor, estadualFor, numFor, tel2For, siteFor, cpfFor, ufFor,tipoproduto;

        ufFor = txt_estadoFor.getText();
        cpfFor = txt_cpfFor.getText();
        cnpjFor = txt_cnpjFor2.getText();
        nomeFantasia = nome_fantasiaFor.getText();
        cnpjFor = txt_cnpjFor2.getText();
        endeFor = txt_endeFor.getText();
        cidadeFor = txt_cidadeFor.getText();
        nomeContato = nome_contatoFor.getText();
        emailFor = txt_emailFor.getText();
        bairroFor = txt_bairroFor.getText();
        telFor = txt_telFor.getText();
        cepFor = txt_cepFor.getText();
        estadualFor = txt_estadualFor.getText();
        celFor = txt_celFor.getText();
        numFor = txt_numFor.getText();
        tel2For = txt_tel2For.getText();
        siteFor = txt_siteFor.getText();
        tipoproduto = comboTipoProduto.getSelectedItem().toString();
        
        
        if(pessoaFisica.isSelected()){
        
        
        if(CPF.isValido(cpfFor) == false || "111.111.111-11".equals(cpfFor)  || "000.000.000-00".equals(cpfFor) || "   .   .   -  ".equals(cpfFor)){

            JOptionPane.showMessageDialog(null,"Preecha  o campo CNPJ corretamente");
            txt_cpfFor.requestFocus();
        }
        else{

            ba.atualizaFornecedorCPF(nomeFantasia, endeFor, cidadeFor, nomeContato, emailFor, bairroFor,cnpjFor, cepFor, telFor, celFor, estadualFor, numFor, tel2For, siteFor, cpfFor, ufFor,tipoproduto);

        }
     }
        
        else if(pessoaJuridica.isSelected()){
        
        
        if(isValido(cnpjFor) == false || "11.111.111/1111-11".equals(cnpjFor) || "  .   .   /    -  ".equals(cnpjFor) || "00.000.000/0000-00".equals(cnpjFor)){

            JOptionPane.showMessageDialog(null,"Preecha  o campo CNPJ corretamente");
            txt_cnpjFor2.requestFocus();
        }
        else{

            ba.atualizaFornecedorCNPJ(nomeFantasia, endeFor, cidadeFor, nomeContato, emailFor, bairroFor,cnpjFor, cepFor, telFor, celFor, estadualFor, numFor, tel2For, siteFor, cpfFor, ufFor, tipoproduto);

        }
               
        
        
       }
    }//GEN-LAST:event_AlterarActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed

        
        //String nomeFantasia = nome_fantasiaFor.getText();
        
        if(pessoaFisica.isSelected()){
            
             
        String cpf =txt_cpfFor.getText();

        if(CPF.isValido(cpf) == false ||"   .   .   -  ".equals(cpf)){

            JOptionPane.showMessageDialog(null,"Preencha o campo CPF corretamente para realizar uma exclusão");
            AlertaCnpj.setVisible(true);
            txt_cpfFor.requestFocus();

        }

        else{
            if (ba.excluiFornecedorCPF(cpf)) {
                JOptionPane.showMessageDialog(null, "Excluido com sucesso");

                limpacampos();

            }
            else {
                JOptionPane.showMessageDialog(null, "Não encontrado");
            }
        }
        }
        
        
                
        else if(pessoaJuridica.isSelected()){
            
             
        String cnpjFor =txt_cnpjFor2.getText();

        if(isValido(cnpjFor) == false||"  .   .    /    -  ".equals(cnpjFor)){

            JOptionPane.showMessageDialog(null,"Preencha o campo CNPJ corretamente para realizar uma exclusão");
            AlertaCnpj.setVisible(true);
            txt_cnpjFor2.requestFocus();

        }

        else{
            if (ba.excluiFornecedorCNPJ(cnpjFor)) {
                JOptionPane.showMessageDialog(null, "Excluido com sucesso");

               limpacampos();

            }
            else {
                JOptionPane.showMessageDialog(null, "Não encontrado");
            }
        }
        }
        
        else{
        
        JOptionPane.showMessageDialog(null, "Selecione se a pessoa é fisica ou juridica");
        
        }
    }//GEN-LAST:event_ExcluirActionPerformed

    private void PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarActionPerformed
        ResultSet rs;

        String cnpj = txt_cnpjFor2.getText();
        String cpf = txt_cpfFor.getText();
        
         if(pessoaFisica.isSelected()){

        
        if("   .   .   -  ".equals(cpf)){

            AlertaCnpj.setVisible(true);
            JOptionPane.showMessageDialog(null,"Preencha o campo Cpf para realizar uma busca");
            txt_cpfFor.requestFocus();
        }

        else{
            AlertaCnpj.setVisible(false);

            rs = ba.buscaFornecedorCPF(cpf);
            try {

                if (ba.buscaFornecedorCPF(cpf) != null) {
                    nome_fantasiaFor.setText(rs.getString("nomeFantasia"));
                    txt_endeFor.setText(rs.getString("endeFor"));
                    txt_cidadeFor.setText(rs.getString("cidadeFor"));
                    nome_contatoFor.setText(rs.getString("nomeContato"));
                    txt_telFor.setText(rs.getString("telFor"));
                    txt_emailFor.setText(rs.getString("emailFor"));
                    txt_bairroFor.setText(rs.getString("bairroFor"));
                    txt_cepFor.setText(rs.getString("cepFor"));
                    txt_numFor.setText(rs.getString("numFor"));
                    txt_celFor.setText(rs.getString("celFor"));
                    txt_tel2For.setText(rs.getString("tel2For"));
                    txt_siteFor.setText(rs.getString("siteFor"));
                    txt_estadoFor.setText(rs.getString("ufFor"));

                    txt_cpfFor.setText(txt_cpfFor.getText());

                    String tipoproduto = rs.getString("tipoproduto");
                  
                    comboTipoProduto.setSelectedItem(tipoproduto);
                    
                }
                else{

                    limpacampos();

                }
            } catch (SQLException ex) {
            }
        }
        
        
    }
        
        
        
        
        
        
        
        
        
        
        
        
        
        

        
        
          if(pessoaJuridica.isSelected()){

        
        if("  .   .   /    -  ".equals(cnpj)){

            AlertaCnpj.setVisible(true);
            JOptionPane.showMessageDialog(null,"Preencha o campo CNPJ para realizar uma busca");
            txt_cnpjFor2.requestFocus();
        }

        else{
            AlertaCnpj.setVisible(false);

            rs = ba.buscaFornecedorCNPJ(cnpj);
            try {

                if (ba.buscaFornecedorCNPJ(cnpj) != null) {
                    nome_fantasiaFor.setText(rs.getString("nomeFantasia"));
                    txt_endeFor.setText(rs.getString("endeFor"));
                    txt_cidadeFor.setText(rs.getString("cidadeFor"));
                    nome_contatoFor.setText(rs.getString("nomeContato"));
                    txt_telFor.setText(rs.getString("telFor"));
                    txt_emailFor.setText(rs.getString("emailFor"));
                    txt_bairroFor.setText(rs.getString("bairroFor"));
                    txt_cepFor.setText(rs.getString("cepFor"));
                    txt_numFor.setText(rs.getString("numFor"));
                    txt_celFor.setText(rs.getString("celFor"));
                    txt_estadualFor.setText(rs.getString("estadualFor"));
                    txt_tel2For.setText(rs.getString("tel2For"));
                    txt_cnpjFor2.setText(txt_cnpjFor2.getText());
                    txt_siteFor.setText(rs.getString("siteFor"));
                }
                else{

                    limpacampos();

                }
            } catch (SQLException ex) {
            }
        }
        
        
    }
   }
  
   private void jTextField1FocusLostCep(java.awt.event.FocusEvent evt) {  
        ResultSet rs;

        String cep = txt_cepFor.getText();

        if("".equals(cep)){

        }

        
        else{
            
            
            rs = bacep.buscaCep(cep);
            try {

                if (bacep.buscaCep(cep) != null) {

                    txt_endeFor.setText(rs.getString("desc_logradouro"));
                    txt_cidadeFor.setText(rs.getString("desc_cidade"));
                    txt_estadoFor.setText(rs.getString("flg_estado"));
                    txt_bairroFor.setText(rs.getString("desc_bairro"));
                    
                }
                else{

                }
            } catch (SQLException ex) {
            }
        } 
        
    }  
   
    private void jTextField1FocusLostCnpj(java.awt.event.FocusEvent evt) {
        String cnpjFor = txt_cnpjFor2.getText();
        String cnpj = cnpjFor;

            if (isValido(cnpjFor) == false || "11.111.111/1111-11".equals(cnpjFor) || "00.000.000/0000-00".equals(cnpjFor) || "  .   .   /    -  ".equals(cnpjFor)  ){


          AlertaCnpj.setVisible(false);

          JOptionPane.showMessageDialog(null,"Atenção CNPJ inválido");
          
          txt_cnpjFor2.requestFocus();
          
          
         }
        else{
         
         ValidaCnpj.formatar(cnpj);
         txt_cnpjFor2.setText(cnpj);
         System.out.println(cnpj);
         
        }
        
    }
    
    private void jTextField1FocusLostCpf(java.awt.event.FocusEvent evt) {
        String cpfFor = txt_cpfFor.getText();
        String cpf = cpfFor;

            if (CPF.isValido(cpfFor) == false || "111.111.111-11".equals(cpfFor) || "000.000.000-00".equals(cpfFor) || "   .   .   -  ".equals(cpfFor)  ){


          AlertaCnpj.setVisible(false);

          JOptionPane.showMessageDialog(null,"Atenção Cpf inválido");
          
          txt_cpfFor.requestFocus();
          
          
         }
        else{
         
         ValidaCnpj.formatar(cpf);
         txt_cnpjFor2.setText(cpf);
         System.out.println(cpf);
         
        }
        
    }
    
    
    
     private void jTextField1FocusLostEmail(java.awt.event.FocusEvent evt) {
        String emailFor = txt_emailFor.getText();
        

        if (Email.isValido(emailFor) == false){
    
          JOptionPane.showMessageDialog(null,"Atenção Email invalido");
          txt_emailFor.requestFocus();

          
         }
  
    
    }//GEN-LAST:event_PesquisarActionPerformed

    private void txt_emailForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailForActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailForActionPerformed

    private void txt_tel2ForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tel2ForActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tel2ForActionPerformed

    private void pessoaFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pessoaFisicaActionPerformed
      if(pessoaFisica.isSelected()){
      
           limpaCamposCPF();
      }
        
        
    }//GEN-LAST:event_pessoaFisicaActionPerformed

    public void preencheCampos(String cpfCnpj){
        
         ResultSet rs;

       
        
         if(CPF.isValido(cpfCnpj) == true){
             
        escondeCamposCPF();
        limpaCamposCPF();
            AlertaCnpj.setVisible(false);

            rs = ba.buscaFornecedorCPF(cpfCnpj);
            try {

                if (ba.buscaFornecedorCPF(cpfCnpj) != null) {
                    
                   
                    
                    
                    txt_cpfFor.setText(rs.getString("cpfFor"));
                    nome_fantasiaFor.setText(rs.getString("nomeFantasia"));
                    txt_endeFor.setText(rs.getString("endeFor"));
                    txt_cidadeFor.setText(rs.getString("cidadeFor"));
                    nome_contatoFor.setText(rs.getString("nomeContato"));
                    txt_telFor.setText(rs.getString("telFor"));
                    txt_emailFor.setText(rs.getString("emailFor"));
                    txt_bairroFor.setText(rs.getString("bairroFor"));
                    txt_cepFor.setText(rs.getString("cepFor"));
                    txt_numFor.setText(rs.getString("numFor"));
                    txt_celFor.setText(rs.getString("celFor"));
                    txt_tel2For.setText(rs.getString("tel2For"));
                    txt_siteFor.setText(rs.getString("siteFor"));
                    txt_estadoFor.setText(rs.getString("ufFor"));

                    txt_cpfFor.setText(txt_cpfFor.getText());

                    String tipoproduto = rs.getString("tipoproduto");
                  
                    comboTipoProduto.setSelectedItem(tipoproduto);
                    
                }
                else{

                    limpacampos();

                }
            } catch (SQLException ex) {
            }
        
         }
        
    
        
        
        
        
        
        
        
        
        
        
        
        
        
        

        
        
         else if(isValido(cpfCnpj) == true){

        
        

            escondeCamposCNPJ();
            limpaCamposCNPJ();
            AlertaCnpj.setVisible(false);

            rs = ba.buscaFornecedorCNPJ(cpfCnpj);
            try {

                if (ba.buscaFornecedorCNPJ(cpfCnpj) != null) {
                    
                    txt_cnpjFor2.setText(rs.getString("cnpjFor"));
                    nome_fantasiaFor.setText(rs.getString("nomeFantasia"));
                    txt_endeFor.setText(rs.getString("endeFor"));
                    txt_cidadeFor.setText(rs.getString("cidadeFor"));
                    nome_contatoFor.setText(rs.getString("nomeContato"));
                    txt_telFor.setText(rs.getString("telFor"));
                    txt_emailFor.setText(rs.getString("emailFor"));
                    txt_bairroFor.setText(rs.getString("bairroFor"));
                    txt_cepFor.setText(rs.getString("cepFor"));
                    txt_numFor.setText(rs.getString("numFor"));
                    txt_celFor.setText(rs.getString("celFor"));
                    txt_estadualFor.setText(rs.getString("estadualFor"));
                    txt_tel2For.setText(rs.getString("tel2For"));
                    txt_cnpjFor2.setText(txt_cnpjFor2.getText());
                    txt_siteFor.setText(rs.getString("siteFor"));
                    
                    String tipoproduto = rs.getString("tipoproduto");
                  
                    comboTipoProduto.setSelectedItem(tipoproduto);
                }
                else{

                    limpacampos();

                }
            } catch (SQLException ex) {
            }
        }
        
        
    }
        
    
    
    
    private void pessoaJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pessoaJuridicaActionPerformed

         if(pessoaJuridica.isSelected()){
      
             limpaCamposCNPJ();
             
      }
        

    }//GEN-LAST:event_pessoaJuridicaActionPerformed

    private void txt_CpfPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CpfPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CpfPesquisaActionPerformed

    private void txt_CnpjPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CnpjPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CnpjPesquisaActionPerformed

    private void radioFisicaPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioFisicaPesquisaActionPerformed
         if(radioFisicaPesquisa.isSelected()){
      
            txt_CpfPesquisa.setText("");
            
            
          
          labelCpfPesquisa.setVisible(true);
          txt_CpfPesquisa.setVisible(true);
          
          
          labelCnpjPesquisa.setVisible(false);
          txt_CnpjPesquisa.setVisible(false);
      }
        
    }//GEN-LAST:event_radioFisicaPesquisaActionPerformed

    private void radioJuridicaPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioJuridicaPesquisaActionPerformed
        if(radioJuridicaPesquisa.isSelected()){
      
             txt_CnpjPesquisa.setText("");
             
             labelCpfPesquisa.setVisible(false);
             txt_CpfPesquisa.setVisible(false);
      

          labelCnpjPesquisa.setVisible(true);
          txt_CnpjPesquisa.setVisible(true);
      }
        
    }//GEN-LAST:event_radioJuridicaPesquisaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            DefaultTableModel modelo = (DefaultTableModel)gridFornecedor.getModel();
       
    gridFornecedor.removeAll();
    
    while(modelo.getRowCount() > 0){
        modelo.removeRow(0);
    }
    String cpf = txt_CpfPesquisa.getText();
    String cnpj = txt_CnpjPesquisa.getText();
    
    ObjetoFornecedor fornecedorpesquisado = new ObjetoFornecedor();
    
      if(radioFisicaPesquisa.isSelected()){
               
    
     if(txt_CpfPesquisa.equals("   .   .   -  ") || CPF.isValido(cpf) == false){
         JOptionPane.showMessageDialog(null,"CPF invalido");
         
     }
     
     else{
     if(txt_CpfPesquisa.getText().isEmpty() == false){
        

      
            fornecedorpesquisado = ba.buscaFornecedorTabelaCPF(String.valueOf(cpf));
            if(fornecedorpesquisado != null){
                modelo.addRow(new Object[]{
                    
                  fornecedorpesquisado.getNomeFantasia(),
                  fornecedorpesquisado.getCpfFor(),
                  fornecedorpesquisado.getEstadualFor(),
                  fornecedorpesquisado.getTipoPessoa(),
                  fornecedorpesquisado.getNomeContato(),
                  fornecedorpesquisado.getTelFor(),
                  fornecedorpesquisado.getTel2For(),
                  fornecedorpesquisado.getCelFor(),
                  fornecedorpesquisado.getUfFor(),
                  fornecedorpesquisado.getCidadeFor(),
                  fornecedorpesquisado.getBairroFor(),
                  fornecedorpesquisado.getEndeFor(),
                  fornecedorpesquisado.getNumFor(),
                  fornecedorpesquisado.getCepFor(),
                  fornecedorpesquisado.getSiteFor(),
                  fornecedorpesquisado.getEmailFor(),
                  fornecedorpesquisado.getTipoproduto(),
                  
                });
            }
            else{
                JOptionPane.showMessageDialog(null, "Nenhum Cliente encontrado !!!");
            }
        
    }
  } 
 }
      
    else if(radioJuridicaPesquisa.isSelected()){
               
    
     if(txt_CnpjPesquisa.equals("  .   .   /   -  ") || isValido(cnpj) == false){
         JOptionPane.showMessageDialog(null,"CNPJ invalido");
         
     }
     
     else{
     if(txt_CnpjPesquisa.getText().isEmpty() == false){
        

      
            fornecedorpesquisado = ba.buscaFornecedorTabelaCNPJ(String.valueOf(cnpj));
            if(fornecedorpesquisado != null){
                modelo.addRow(new Object[]{
                 
                  fornecedorpesquisado.getNomeFantasia(), 
                  fornecedorpesquisado.getCnpjFor(),
                  fornecedorpesquisado.getEstadualFor(),
                  fornecedorpesquisado.getTipoPessoa(),
                  fornecedorpesquisado.getNomeContato(),
                  fornecedorpesquisado.getTelFor(),
                  fornecedorpesquisado.getTel2For(),
                  fornecedorpesquisado.getCelFor(),
                  fornecedorpesquisado.getUfFor(),
                  fornecedorpesquisado.getCidadeFor(),
                  fornecedorpesquisado.getBairroFor(),
                  fornecedorpesquisado.getEndeFor(),
                  fornecedorpesquisado.getNumFor(),
                  fornecedorpesquisado.getCepFor(),
                  fornecedorpesquisado.getSiteFor(),
                  fornecedorpesquisado.getEmailFor(),
                  fornecedorpesquisado.getTipoproduto()
                });
            }
            else{
                JOptionPane.showMessageDialog(null, "Nenhum Fornecedor encontrado !!!");
            }
        
    }
  } 
 }  
    
    else{
    
        JOptionPane.showMessageDialog(null,"Selecione o tipo de pessoa");
        
    }
    
      
      
    gridFornecedor.repaint();
    
    txt_CpfPesquisa.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void gridFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gridFornecedorMouseClicked
       
          
        if (evt.getClickCount() == 2) {  
            
         
            
            Object obj1 = (gridFornecedor.getValueAt(gridFornecedor.getSelectedRow(), 1));  //coluna 0  
            String cnpjcpf = obj1.toString();
            
            preencheCampos(cnpjcpf);
        
           
           
            
            
               // QUANDO SELECIONA A LINHA NA JTABLE MUDA A ABA
              TabFornecedor.setSelectedIndex(0);   
             
        }
        
        
        
    }//GEN-LAST:event_gridFornecedorMouseClicked

    private void txt_cnpjFor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cnpjFor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cnpjFor2ActionPerformed

    private void txt_cpfForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cpfForActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cpfForActionPerformed

    private void TabFornecedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabFornecedorMousePressed

        carregaTabela();
        
    }//GEN-LAST:event_TabFornecedorMousePressed
    public void escondeCamposCNPJ(){
        
        
                
                pessoaJuridica.setSelected(true);
               
                txt_cpfFor.setVisible(true);
                
              
      
             
             labelCpf.setVisible(false);
             txt_cpfFor.setVisible(false);
          labelEstadual.setVisible(true);
          txt_estadualFor.setVisible(true);
          txt_cnpjFor2.setVisible(true);
          labelCnpj.setVisible(true);
        
    }
    
    public void escondeCamposCPF(){
        
            pessoaFisica.setSelected(true);
            
                
          labelCpf.setVisible(true);
          txt_cpfFor.setVisible(true);
          labelEstadual.setVisible(false);
          txt_estadualFor.setVisible(false);
          
          labelCnpj.setVisible(false);
          txt_cnpjFor2.setVisible(false);
        
    }
    
    
    public void limpaCamposCPF(){
         txt_cpfFor.setText("");
          txt_cnpjFor2.setText("");
          labelCpf.setVisible(true);
          txt_cpfFor.setVisible(true);
          labelEstadual.setVisible(false);
          txt_estadualFor.setVisible(false);
          
          labelCnpj.setVisible(false);
          txt_cnpjFor2.setVisible(false);
        
    }
    
    public void limpaCamposCNPJ(){
        
        
             txt_cnpjFor2.setText("");
             txt_cpfFor.setText("");
             labelCpf.setVisible(false);
             txt_cpfFor.setVisible(false);
          labelEstadual.setVisible(true);
          txt_estadualFor.setVisible(true);
          txt_cnpjFor2.setVisible(true);
          labelCnpj.setVisible(true);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlertaCnpj;
    private javax.swing.JButton Alterar;
    private javax.swing.JButton Excluir;
    private javax.swing.JButton Gravar;
    private javax.swing.JButton Novo;
    private javax.swing.JButton Pesquisar;
    private javax.swing.JTabbedPane TabFornecedor;
    private javax.swing.JComboBox comboTipoProduto;
    private javax.swing.JTable gridFornecedor;
    private javax.swing.ButtonGroup grupoRadio;
    private javax.swing.ButtonGroup grupoRadioPesquisa;
    public javax.swing.JInternalFrame internalFornecedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JLabel labelCnpj;
    private javax.swing.JLabel labelCnpjPesquisa;
    private javax.swing.JLabel labelCpf;
    private javax.swing.JLabel labelCpfPesquisa;
    private javax.swing.JLabel labelEstadual;
    private javax.swing.JTextField nome_contatoFor;
    private javax.swing.JTextField nome_fantasiaFor;
    private javax.swing.JRadioButton pessoaFisica;
    private javax.swing.JRadioButton pessoaJuridica;
    private javax.swing.JRadioButton radioFisicaPesquisa;
    private javax.swing.JRadioButton radioJuridicaPesquisa;
    private javax.swing.JFormattedTextField txt_CnpjPesquisa;
    private javax.swing.JFormattedTextField txt_CpfPesquisa;
    private javax.swing.JTextField txt_bairroFor;
    private javax.swing.JFormattedTextField txt_celFor;
    private javax.swing.JTextField txt_cepFor;
    private javax.swing.JTextField txt_cidadeFor;
    private javax.swing.JFormattedTextField txt_cnpjFor2;
    private javax.swing.JFormattedTextField txt_cpfFor;
    private javax.swing.JTextField txt_emailFor;
    private javax.swing.JTextField txt_endeFor;
    private javax.swing.JTextField txt_estadoFor;
    private javax.swing.JFormattedTextField txt_estadualFor;
    private javax.swing.JTextField txt_numFor;
    private javax.swing.JTextField txt_siteFor;
    private javax.swing.JFormattedTextField txt_tel2For;
    private javax.swing.JFormattedTextField txt_telFor;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the combo
     */
    public String getCombo() {
        return combo = (String) comboTipoProduto.getSelectedItem();
    }

    /**
     * @param combo the combo to set
     */
    public void setCombo(String combo) {
        this.combo = combo;
    }
    
    public void carregaTipoPruduto(){
        String msg1 = "Fornecedores recuperados";
        String msg2 = "Erro ao Recuperar Fornecedores";
        String vsql = "SELECT categoria FROM categoriaProduto order by categoria";
        String campoSql = "categoria";

        bf.carregaDadoUnico(vsql, msg1, msg2, comboTipoProduto, campoSql);
    }
    
    
     public void carregaTabela(){
        String msg1 = "Fornecedor recuperados com sucesso";
        String msg2 = "Erro ao Recuperar Fornecedor";
        String vsql = "SELECT * from fornecedor order by nomeFantasia";


        bf.tabelaFornecedor(vsql, msg1, msg2, gridFornecedor);
    }
}
